import {
  DashboardSummary,
  ReportItem,
  ReportDetail,
  Barrier,
  Site,
  Activity,
  LSR,
  PrecursorCluster,
  AuditEntry,
  AlertItem,
  ModelHealth,
} from "./api";

export const FALLBACK_SITES: Site[] = [
  { id: "site-001", code: "MHN-OFFSHORE", name: "Mumbai High North Platform", location: "Western Offshore Basin, Maharashtra", operational_unit: "Offshore Production", risk_level: "HIGH" },
  { id: "site-002", code: "DGB-REFINERY", name: "Digboi Refinery Complex", location: "Tinsukia District, Assam", operational_unit: "Crude Distillation Unit (CDU-II)", risk_level: "CRITICAL" },
  { id: "site-003", code: "HZR-TERMINAL", name: "Hazira LNG Regasification Terminal", location: "Surat District, Gujarat", operational_unit: "Cryogenic Boil-off & Compression", risk_level: "HIGH" },
  { id: "site-004", code: "BMR-UPSTREAM", name: "Barmer Oil Gathering Station (OGS-3)", location: "Thar Basin, Rajasthan", operational_unit: "Enhanced Oil Recovery (Thermal/Polymer)", risk_level: "MEDIUM" },
  { id: "site-005", code: "PDC-PETROCHEM", name: "Paradip Petrochemicals & FCC Complex", location: "Jagatsinghpur, Odisha", operational_unit: "Fluidized Catalytic Cracking Unit", risk_level: "CRITICAL" },
];

export const FALLBACK_ACTIVITIES: Activity[] = [
  { id: "act-001", code: "HOT-WORK", name: "Hot Work & High-Energy Welding", category: "High Hazard", description: "Oxy-acetylene cutting, structural stick welding, and grinding near live process streams." },
  { id: "act-002", code: "CONFINED-SPACE", name: "Confined Space & Vessel Entry", category: "Critical", description: "Internal inspection and sludge cleaning in hydrocarbon storage bullets and distillation columns." },
  { id: "act-003", code: "ISOLATION-LOTO", name: "Positive Isolation & LOTO Blind Insertion", category: "Critical", description: "Double block and bleed verification and slip-blind bolting on high-pressure manifolds." },
  { id: "act-004", code: "HEAVY-LIFTING", name: "Offshore Crane Heavy Lift Operations", category: "Hazardous", description: "Supply boat cargo transfer and pedestal crane lifts over live subsea pipelines." },
  { id: "act-005", code: "HIGH-PRESSURE-PIGGING", name: "Pipeline Pigging & Receiver Operations", category: "High Hazard", description: "Intelligent pig receiver barrel depressurization and quick-opening door opening." },
];

export const FALLBACK_BARRIERS: Barrier[] = [
  { id: "bar-001", code: "BAR-ENG-01", name: "Positive Physical Isolation (Double Block & Bleed)", category: "Engineered", expected_function: "Zero energy state isolation via verified bleed point and mechanical blinds." },
  { id: "bar-002", code: "BAR-ENG-02", name: "Emergency Shutdown Valve (SDV/ESD Automation)", category: "Engineered", expected_function: "Automatic isolation of hydrocarbon inventories within 12 seconds of high-pressure trip." },
  { id: "bar-003", code: "BAR-ENG-03", name: "LEL Flammable & H2S Optical Gas Detectors", category: "Engineered", expected_function: "Continuous combustible gas perimeter monitoring with 2-out-of-3 voting logic." },
  { id: "bar-004", code: "BAR-ENG-04", name: "Pressure Safety Relief Valve (PSV) Discharge", category: "Engineered", expected_function: "Overpressure thermal relief routed safely to the high-pressure flare header." },
  { id: "bar-005", code: "BAR-ENG-05", name: "Deluge & Firewater Foam Suppression", category: "Engineered", expected_function: "High-rate area cooling and vapor cloud mitigation on manifold skid bays." },
  { id: "bar-006", code: "BAR-PROC-01", name: "Permit to Work (PTW) Simultaneous Operations Check", category: "Procedural", expected_function: "SIMOPS clash analysis and permit issuer physical site walk before ignition permit issuance." },
  { id: "bar-007", code: "BAR-PROC-02", name: "Lockout-Tagout (LOTO) & Key Interlock Protocol", category: "Procedural", expected_function: "Master lockbox custody verification preventing premature re-energization." },
  { id: "bar-008", code: "BAR-PROC-03", name: "Pre-Entry Gas Free Certification & Continuous Sniffing", category: "Procedural", expected_function: "Oxygen 20.9%, H2S < 5 ppm, LEL 0.0% validation every 60 minutes." },
  { id: "bar-009", code: "BAR-HUM-01", name: "Shift Fatigue Management & Maximum Work Hours", category: "Human", expected_function: "Strict 12-hour limit with mandatory 8-hour rest cycle during offshore turnaround." },
  { id: "bar-010", code: "BAR-HUM-02", name: "Dual Competency Sign-off for Critical Isolations", category: "Human", expected_function: "Independent peer verification of blind flange torque and slip spectacle plate orientation." },
];

export const FALLBACK_LSRS: LSR[] = [
  { id: "lsr-01", code: "LSR-01", name: "Bypassing Safety Controls", icon_name: "ShieldAlert", description: "Obtain authorization before overriding or disabling safety controls.", guidance: "Never bypass an ESD or interlock without MOC approval." },
  { id: "lsr-02", code: "LSR-02", name: "Confined Space Entry", icon_name: "DoorClosed", description: "Obtain authorization before entering a confined space.", guidance: "Verify atmosphere is gas-free and rescue plan is staged." },
  { id: "lsr-03", code: "LSR-03", name: "Energy Isolation", icon_name: "ZapOff", description: "Verify isolation and zero energy before beginning work.", guidance: "Always test before touch: try starting isolated equipment." },
  { id: "lsr-04", code: "LSR-04", name: "Hot Work Control", icon_name: "Flame", description: "Control flammables and ignition sources in hazardous zones.", guidance: "Continuous LEL monitoring required within 15 meters." },
  { id: "lsr-05", code: "LSR-05", name: "Line of Fire", icon_name: "Target", description: "Position yourself and others outside hazardous release zones.", guidance: "Never stand below suspended loads or near pressurized flanges." },
  { id: "lsr-06", code: "LSR-06", name: "Safe Mechanical Lifting", icon_name: "Anchor", description: "Plan lifting operations and control the area.", guidance: "Verify crane load charts and certified rigging hardware." },
  { id: "lsr-07", code: "LSR-07", name: "Work Authorization & PTW", icon_name: "FileCheck", description: "Work with a valid permit when required.", guidance: "Never commence work without verified gas tests and field walk." },
  { id: "lsr-08", code: "LSR-08", name: "Working at Height", icon_name: "ArrowUpRight", description: "Protect yourself against falling when working above 1.8 meters.", guidance: "100% tie-off with dual-lanyard shock-absorbing harness." },
  { id: "lsr-09", code: "LSR-09", name: "Toxic Gas Protection (H2S)", icon_name: "Skull", description: "Wear personal H2S detectors and know emergency escape routes.", guidance: "Immediately don EEBD mask upon first audible chirp." },
];

export const FALLBACK_REPORTS: ReportDetail[] = [
  {
    id: "rep-001",
    report_uid: "MHN-2026-0089",
    report_type: "Near-Miss Precursor",
    date_time: "2026-09-12 14:35:00",
    site_name: "Mumbai High North Platform",
    activity_name: "Valve Isolation & Maintenance",
    narrative_snippet: "During scheduled maintenance on Gas Lift Manifold GLM-04, contractor technician noted continuous weeping of pressurized hydrocarbon condensate from upstream block valve bonnet seal.",
    narrative: "During scheduled maintenance on Gas Lift Manifold GLM-04 at Mumbai High North, contractor technician noted continuous weeping of pressurized hydrocarbon condensate from upstream block valve bonnet seal. Flange bolts exhibited severe marine atmospheric corrosion. The line operates at 110 bar gas-lift injection pressure. Work was immediately suspended, double block and bleed integrity was re-inspected, and area was depopulated until emergency depressurization was completed via flare header.",
    equipment: "Gas Lift Manifold GLM-04 (110 Bar)",
    location: "Deck 2 Wellhead Area, Sector B",
    contractor_internal: "L&T Hydrocarbon Engineering",
    actual_outcome: "Minor condensate weepage onto drip tray, no ignition occurred.",
    potential_consequence: "Uncontrolled high-pressure gas blowout with jet fire risking platform evacuation.",
    psif_probability: 0.84,
    priority_score: 92,
    primary_barrier: "Positive Physical Isolation (Double Block & Bleed)",
    barrier_state: "FAILED",
    primary_lsr: "Energy Isolation (LSR-03)",
    review_status: "UNDER_INVESTIGATION",
    data_origin: "FIELD_LOG",
    entities: [
      { entity_type: "EQUIPMENT", value: "Gas Lift Manifold GLM-04", text_span: "Gas Lift Manifold GLM-04", confidence: 0.96 },
      { entity_type: "HAZARD", value: "110 bar gas-lift injection pressure", text_span: "110 bar gas-lift injection pressure", confidence: 0.94 },
      { entity_type: "CONDITION", value: "marine atmospheric corrosion", text_span: "marine atmospheric corrosion", confidence: 0.91 },
      { entity_type: "BARRIER", value: "double block and bleed", text_span: "double block and bleed", confidence: 0.95 },
    ],
    psif_prediction: {
      psif_probability: 0.84,
      priority_score: 92,
      confidence: 0.93,
      is_calibrated: true,
      primary_barrier: "Positive Physical Isolation (Double Block & Bleed)",
      barrier_state: "FAILED",
      credible_consequence: "High-pressure hydrocarbon blowout and potential vapor cloud explosion (VCE).",
      explanation_summary: "High operating pressure (110 bar) coupled with active valve packing failure in an offshore wellhead compartment creates severe SIF precursor potential.",
      shap_values: {
        "High Operating Pressure (>80 bar)": 0.38,
        "Barrier Degradation (DBB Bleed)": 0.29,
        "Corroded Marine Fasteners": 0.17,
        "Hot Work Proximity (SIMOPS)": 0.08,
      },
    },
    lsr_predictions: [
      { lsr_id: "lsr-03", code: "LSR-03", name: "Energy Isolation", confidence: 0.95, rank: 1 },
      { lsr_id: "lsr-01", code: "LSR-01", name: "Bypassing Safety Controls", confidence: 0.72, rank: 2 },
    ],
  },
  {
    id: "rep-002",
    report_uid: "DGB-2026-0014",
    report_type: "Hazard Observation",
    date_time: "2026-09-13 09:15:00",
    site_name: "Digboi Refinery Complex",
    activity_name: "Hot Work & High-Energy Welding",
    narrative_snippet: "Pre-hot-work gas sniffer test detected 18% LEL volatile hydrocarbons in drainage trench adjacent to Crude Distillation Column C-102 while structural welding was authorized 4 meters away.",
    narrative: "Pre-hot-work gas sniffer test detected 18% LEL volatile hydrocarbons in drainage trench adjacent to Crude Distillation Column C-102 at Digboi Refinery while structural welding was authorized 4 meters away. Fire watch was not equipped with continuous optical gas detector. Permit was recalled and sewer drain water-seal was replenished.",
    equipment: "Crude Distillation Column C-102 & Trench T-4",
    location: "CDU-II Process Battery Limit",
    contractor_internal: "Internal Maintenance Crew",
    actual_outcome: "Gas detected before ignition source applied.",
    potential_consequence: "Flash fire in open oily water sewer trench with personnel burn injuries.",
    psif_probability: 0.78,
    priority_score: 86,
    primary_barrier: "LEL Flammable & H2S Optical Gas Detectors",
    barrier_state: "DEGRADED",
    primary_lsr: "Hot Work Control (LSR-04)",
    review_status: "VERIFIED",
    data_origin: "FIELD_LOG",
    entities: [
      { entity_type: "EQUIPMENT", value: "Crude Distillation Column C-102", text_span: "Crude Distillation Column C-102", confidence: 0.94 },
      { entity_type: "HAZARD", value: "18% LEL volatile hydrocarbons", text_span: "18% LEL volatile hydrocarbons", confidence: 0.97 },
      { entity_type: "ACTIVITY", value: "structural welding", text_span: "structural welding", confidence: 0.92 },
    ],
    psif_prediction: {
      psif_probability: 0.78,
      priority_score: 86,
      confidence: 0.89,
      is_calibrated: true,
      primary_barrier: "LEL Flammable & H2S Optical Gas Detectors",
      barrier_state: "DEGRADED",
      credible_consequence: "Trench flash fire propagating to crude pre-heat exchanger train.",
      shap_values: {
        "Flammable Vapor (>10% LEL)": 0.44,
        "Active Hot Work Spark Source": 0.26,
        "Inadequate Fire Watch Sniffing": 0.18,
      },
    },
    lsr_predictions: [
      { lsr_id: "lsr-04", code: "LSR-04", name: "Hot Work Control", confidence: 0.94, rank: 1 },
      { lsr_id: "lsr-07", code: "LSR-07", name: "Work Authorization & PTW", confidence: 0.81, rank: 2 },
    ],
  },
  {
    id: "rep-003",
    report_uid: "HZR-2026-0052",
    report_type: "Equipment Failure",
    date_time: "2026-09-14 11:40:00",
    site_name: "Hazira LNG Regasification Terminal",
    activity_name: "High-Pressure Pipeline Pigging",
    narrative_snippet: "BOG (Boil-off Gas) Compressor K-201B dry gas seal secondary vent pressure tripped alarm at 3.8 bar. Manual bypass had been enabled during instrument calibration without MOC authorization.",
    narrative: "BOG (Boil-off Gas) Compressor K-201B dry gas seal secondary vent pressure tripped alarm at 3.8 bar. Manual bypass of the ESD trip interlock had been enabled during instrument calibration earlier that morning without MOC authorization. Flare knock-out drum level was elevated.",
    equipment: "BOG Compressor K-201B (Elliott Cryogenic)",
    location: "Compression Shed Bay 3",
    contractor_internal: "Siemens Energy Service",
    actual_outcome: "Compressor manually tripped by console supervisor after 6 minutes.",
    potential_consequence: "Dry gas seal blowout resulting in major cryogenic methane vapor cloud release.",
    psif_probability: 0.91,
    priority_score: 96,
    primary_barrier: "Emergency Shutdown Valve (SDV/ESD Automation)",
    barrier_state: "FAILED",
    primary_lsr: "Bypassing Safety Controls (LSR-01)",
    review_status: "VERIFIED",
    data_origin: "SCADA_ALARM",
    entities: [
      { entity_type: "EQUIPMENT", value: "BOG Compressor K-201B", text_span: "BOG Compressor K-201B", confidence: 0.98 },
      { entity_type: "HAZARD", value: "secondary vent pressure 3.8 bar", text_span: "secondary vent pressure", confidence: 0.91 },
      { entity_type: "VIOLATION", value: "Manual bypass without MOC", text_span: "Manual bypass", confidence: 0.95 },
    ],
    psif_prediction: {
      psif_probability: 0.91,
      priority_score: 96,
      confidence: 0.96,
      is_calibrated: true,
      primary_barrier: "Emergency Shutdown Valve (SDV/ESD Automation)",
      barrier_state: "FAILED",
      credible_consequence: "Catastrophic cryogenic seal rupture and unconfined vapor cloud explosion.",
      shap_values: {
        "Defeated Safety Interlock (Bypass)": 0.48,
        "Cryogenic Gas Inventory": 0.28,
        "Unattended Calibration Mode": 0.15,
      },
    },
    lsr_predictions: [
      { lsr_id: "lsr-01", code: "LSR-01", name: "Bypassing Safety Controls", confidence: 0.98, rank: 1 },
      { lsr_id: "lsr-03", code: "LSR-03", name: "Energy Isolation", confidence: 0.76, rank: 2 },
    ],
  },
  {
    id: "rep-004",
    report_uid: "BMR-2026-0031",
    report_type: "Near-Miss Precursor",
    date_time: "2026-09-14 16:10:00",
    site_name: "Barmer Oil Gathering Station (OGS-3)",
    activity_name: "Positive Isolation & LOTO Blind Insertion",
    narrative_snippet: "During crude oil transfer line tie-in, pipefitter found slip blind installed backwards with open spacer exposed to active pressure line due to worn marking paint on spectacle blind.",
    narrative: "During crude oil transfer line tie-in at Barmer OGS-3, pipefitter found slip blind installed backwards with open spacer exposed to active pressure line due to worn marking paint on spectacle blind. Line was pressurized to 45 bar with heated waxy crude (75°C).",
    equipment: "Spectacle Blind SB-14A & Trunkline TL-02",
    location: "Manifold Skid East",
    contractor_internal: "Punj Lloyd Infrastructure",
    actual_outcome: "Discovered during walkdown prior to valve crack opening.",
    potential_consequence: "Hot waxy crude spray at 45 bar causing severe thermal burns and pool fire.",
    psif_probability: 0.72,
    priority_score: 81,
    primary_barrier: "Dual Competency Sign-off for Critical Isolations",
    barrier_state: "DEGRADED",
    primary_lsr: "Energy Isolation (LSR-03)",
    review_status: "VERIFIED",
    data_origin: "FIELD_LOG",
    entities: [
      { entity_type: "EQUIPMENT", value: "Spectacle Blind SB-14A", text_span: "Spectacle Blind SB-14A", confidence: 0.95 },
      { entity_type: "HAZARD", value: "45 bar heated waxy crude 75°C", text_span: "45 bar heated waxy crude", confidence: 0.94 },
    ],
    psif_prediction: {
      psif_probability: 0.72,
      priority_score: 81,
      confidence: 0.91,
      is_calibrated: true,
      primary_barrier: "Dual Competency Sign-off for Critical Isolations",
      barrier_state: "DEGRADED",
      shap_values: {
        "Heated Pressurized Fluid": 0.36,
        "Human Error (Inverted Blind)": 0.32,
        "Sign-off Process Gap": 0.14,
      },
    },
    lsr_predictions: [
      { lsr_id: "lsr-03", code: "LSR-03", name: "Energy Isolation", confidence: 0.92, rank: 1 },
    ],
  },
  {
    id: "rep-005",
    report_uid: "PDC-2026-0077",
    report_type: "Hazard Observation",
    date_time: "2026-09-15 08:20:00",
    site_name: "Paradip Petrochemicals & FCC Complex",
    activity_name: "Confined Space & Vessel Entry",
    narrative_snippet: "Entry attendants noted standby breathing air bottle manifold pressure dropping intermittently from 200 bar to 40 bar during reactor vessel R-301 catalyst bed inspection.",
    narrative: "Entry attendants noted standby breathing air bottle manifold pressure dropping intermittently from 200 bar to 40 bar during reactor vessel R-301 catalyst bed inspection at Paradip FCC. Air supply regulator had loose quick-connect coupling. Two entrants inside nitrogen-inerted atmosphere were evacuated immediately.",
    equipment: "Breathing Air Manifold BAM-02 & Reactor R-301",
    location: "FCC Reactor Structure Level 4",
    contractor_internal: "Technip Energies Contracting",
    actual_outcome: "Entrants safely egressed within 90 seconds without hypoxia symptoms.",
    potential_consequence: "Nitrogen asphyxiation inside confined catalyst reactor resulting in multiple fatalities.",
    psif_probability: 0.94,
    priority_score: 98,
    primary_barrier: "Pre-Entry Gas Free Certification & Continuous Sniffing",
    barrier_state: "FAILED",
    primary_lsr: "Confined Space Entry (LSR-02)",
    review_status: "UNDER_INVESTIGATION",
    data_origin: "FIELD_LOG",
    entities: [
      { entity_type: "EQUIPMENT", value: "Breathing Air Manifold BAM-02", text_span: "Breathing Air Manifold BAM-02", confidence: 0.97 },
      { entity_type: "HAZARD", value: "nitrogen-inerted atmosphere", text_span: "nitrogen-inerted atmosphere", confidence: 0.98 },
    ],
    psif_prediction: {
      psif_probability: 0.94,
      priority_score: 98,
      confidence: 0.97,
      is_calibrated: true,
      primary_barrier: "Pre-Entry Gas Free Certification & Continuous Sniffing",
      barrier_state: "FAILED",
      credible_consequence: "Immediate nitrogen asphyxiation (zero oxygen survival < 3 minutes).",
      shap_values: {
        "IDLH Inert Atmosphere (N2)": 0.52,
        "Life-Support Air System Degradation": 0.34,
        "Confined Space Geometry": 0.12,
      },
    },
    lsr_predictions: [
      { lsr_id: "lsr-02", code: "LSR-02", name: "Confined Space Entry", confidence: 0.99, rank: 1 },
    ],
  },
];

export const FALLBACK_PRECURSORS: PrecursorCluster[] = [
  {
    id: "prec-001",
    name: "High-Pressure Gas Lift Flange & Packing Weeps",
    summary: "Repeated small-scale gas and condensate weepage from 90-110 bar injection manifolds during offshore vibration cycles.",
    coherence_score: 0.91,
    occurrence_count: 8,
    primary_hazard: "Loss of Containment (Pressurized Methane)",
    primary_barrier: "Positive Physical Isolation (Double Block & Bleed)",
    primary_lsr: "Energy Isolation (LSR-03)",
    trend_status: "INCREASING",
    first_seen: "2026-08-10",
    latest_seen: "2026-09-14",
    affected_sites: ["Mumbai High North Platform", "Barmer Oil Gathering Station (OGS-3)"],
    affected_activities: ["Valve Isolation & Maintenance", "High-Pressure Pipeline Pigging"],
    example_report_ids: ["rep-001", "rep-004"],
  },
  {
    id: "prec-002",
    name: "Permit to Work & Hot Work Ignition Boundary Gaps",
    summary: "Residual light hydrocarbon vapors detected in drainage sumps and trenches within 5 meters of active torch cutting.",
    coherence_score: 0.88,
    occurrence_count: 6,
    primary_hazard: "Vapor Cloud Flash Fire",
    primary_barrier: "LEL Flammable & H2S Optical Gas Detectors",
    primary_lsr: "Hot Work Control (LSR-04)",
    trend_status: "STABLE",
    first_seen: "2026-08-15",
    latest_seen: "2026-09-13",
    affected_sites: ["Digboi Refinery Complex", "Paradip Petrochemicals & FCC Complex"],
    affected_activities: ["Hot Work & High-Energy Welding"],
    example_report_ids: ["rep-002"],
  },
  {
    id: "prec-003",
    name: "Rotating Equipment ESD Bypass During Calibration",
    summary: "Temporary instrumentation override jumpers left active on critical compressor trips without formal MOC sign-off.",
    coherence_score: 0.94,
    occurrence_count: 4,
    primary_hazard: "Uncontrolled Overpressure / Catastrophic Seal Failure",
    primary_barrier: "Emergency Shutdown Valve (SDV/ESD Automation)",
    primary_lsr: "Bypassing Safety Controls (LSR-01)",
    trend_status: "ELEVATED",
    first_seen: "2026-09-01",
    latest_seen: "2026-09-14",
    affected_sites: ["Hazira LNG Regasification Terminal"],
    affected_activities: ["High-Pressure Pipeline Pigging"],
    example_report_ids: ["rep-003"],
  },
  {
    id: "prec-004",
    name: "Inert Gas Life-Support Coupling Anomalies",
    summary: "Breathing air pressure dips and hose fittings degrading during nitrogen-blanketed catalyst bed entries.",
    coherence_score: 0.87,
    occurrence_count: 5,
    primary_hazard: "Nitrogen Asphyxiation (IDLH)",
    primary_barrier: "Pre-Entry Gas Free Certification & Continuous Sniffing",
    primary_lsr: "Confined Space Entry (LSR-02)",
    trend_status: "HIGH_RISK",
    first_seen: "2026-08-20",
    latest_seen: "2026-09-15",
    affected_sites: ["Paradip Petrochemicals & FCC Complex", "Digboi Refinery Complex"],
    affected_activities: ["Confined Space & Vessel Entry"],
    example_report_ids: ["rep-005"],
  },
];

export const FALLBACK_AUDIT_LOG: AuditEntry[] = [
  {
    id: "aud-001",
    timestamp: "2026-09-15T13:45:10Z",
    user_id: "usr-001",
    user_name: "Priya Sharma",
    user_email: "analyst@suraksha.ai",
    user_role: "HSE_ANALYST",
    action: "VERIFY_PSIF_SCORE",
    entity_type: "REPORT",
    entity_id: "MHN-2026-0089",
    details: { pSIF_score: 0.84, action_taken: "Escalated to Offshore Asset Manager" },
    ip_address: "10.14.82.11",
  },
  {
    id: "aud-002",
    timestamp: "2026-09-15T12:20:00Z",
    user_id: "usr-002",
    user_name: "Rajesh Verma",
    user_email: "manager@suraksha.ai",
    user_role: "HSE_MANAGER",
    action: "CONFIRM_BARRIER_OVERRIDE",
    entity_type: "BARRIER",
    entity_id: "BAR-ENG-02",
    details: { site: "Hazira LNG Terminal", reason: "MOC-2026-091 approved for dry gas seal replacement" },
    ip_address: "10.14.82.25",
  },
  {
    id: "aud-003",
    timestamp: "2026-09-15T11:05:44Z",
    user_id: "usr-003",
    user_name: "Dr. Aris Thorne",
    user_email: "scientist@suraksha.ai",
    user_role: "DATA_SCIENTIST",
    action: "VALIDATE_MODEL_CALIBRATION",
    entity_type: "MODEL",
    entity_id: "psif-xgboost-v2.4",
    details: { pr_auc: 0.88, calibration_method: "Platt Sigmoid", status: "HEALTHY" },
    ip_address: "10.14.90.104",
  },
  {
    id: "aud-004",
    timestamp: "2026-09-15T09:30:12Z",
    user_id: "usr-004",
    user_name: "Vikramaditya Sen",
    user_email: "admin@suraksha.ai",
    user_role: "ADMINISTRATOR",
    action: "SYSTEM_DIAGNOSTICS_INSPECTION",
    entity_type: "INFRASTRUCTURE",
    entity_id: "sovereign-ollama-cluster",
    details: { node_health: "OPTIMAL", local_models: ["mistral", "llama3"] },
    ip_address: "10.14.80.1",
  },
];

export const FALLBACK_ALERTS: AlertItem[] = [
  {
    id: "alt-001",
    alert_type: "CRITICAL_BARRIER_FAIL",
    severity: "CRITICAL",
    title: "Double Block & Bleed Failure on 110 Bar Gas Lift",
    message: "Report MHN-2026-0089 confirmed active passing on block valve bonnet seal at Mumbai High North.",
    report_id: "rep-001",
    is_acknowledged: false,
    created_at: "2026-09-15T12:00:00Z",
  },
  {
    id: "alt-002",
    alert_type: "UNAUTHORIZED_BYPASS",
    severity: "CRITICAL",
    title: "Unapproved ESD Override on BOG Compressor",
    message: "Hazira Terminal report HZR-2026-0052 indicates interlock trip bypass without verified MOC documentation.",
    report_id: "rep-003",
    is_acknowledged: false,
    created_at: "2026-09-15T11:45:00Z",
  },
  {
    id: "alt-003",
    alert_type: "IDLH_ATMOSPHERE_LEAK",
    severity: "HIGH",
    title: "Breathing Air Manifold Pressure Dip in Nitrogen Vessel",
    message: "Paradip complex vessel entry R-301 attendant flagged secondary air regulator pressure drop.",
    report_id: "rep-005",
    is_acknowledged: false,
    created_at: "2026-09-15T08:30:00Z",
  },
];

export const FALLBACK_DASHBOARD_SUMMARY: DashboardSummary = {
  total_reports: 33,
  psif_priority_count: 8,
  pending_reviews: 5,
  active_barriers: 18,
  unacknowledged_alerts: 3,
  barrier_states: {
    VERIFIED: 22,
    UNVERIFIED: 8,
    FAILED: 3,
  },
  monthly_trend: [
    { month: "May 2026", total_reports: 18, psif_priority: 3, psif_density: 0.16 },
    { month: "Jun 2026", total_reports: 24, psif_priority: 5, psif_density: 0.20 },
    { month: "Jul 2026", total_reports: 29, psif_priority: 6, psif_density: 0.21 },
    { month: "Aug 2026", total_reports: 31, psif_priority: 7, psif_density: 0.22 },
    { month: "Sep 2026", total_reports: 33, psif_priority: 8, psif_density: 0.24 },
  ],
  barrier_health: [
    { name: "Double Block & Bleed Isolation", code: "BAR-ENG-01", verified: 28, unverified: 3, failed: 2 },
    { name: "Emergency Shutdown Valves", code: "BAR-ENG-02", verified: 31, unverified: 1, failed: 1 },
    { name: "LEL Optical Gas Detectors", code: "BAR-ENG-03", verified: 29, unverified: 4, failed: 0 },
    { name: "Permit to Work Verification", code: "BAR-PROC-01", verified: 30, unverified: 2, failed: 1 },
    { name: "Confined Space Gas Free Testing", code: "BAR-PROC-03", verified: 26, unverified: 5, failed: 2 },
  ],
  top_alerts: FALLBACK_ALERTS,
  recent_activity: FALLBACK_AUDIT_LOG,
  ollama_status: "connected",
  ollama_mode: "SOVEREIGN_ON_PREMISE",
  available_models: ["mistral:7b-instruct", "llama3:8b-instruct", "qwen2.5:7b-safety"],
};

export const FALLBACK_MODEL_HEALTH: ModelHealth = {
  nlp: {
    model: "Transformer NER (Indian O&G Specialized)",
    version: "2.4.1",
    average_latency_ms: 18.4,
    status: "HEALTHY",
    extraction_confidence_avg: 0.94,
  },
  psif: {
    model: "Calibrated Gradient Boosted Ensemble",
    version: "3.1.0",
    calibration_method: "Platt Sigmoid Scaling",
    is_calibrated: true,
    calibration_percentage: 100,
    pr_auc: 0.88,
    f2_score: 0.86,
    total_evaluated_records: 1240,
    status: "HEALTHY",
  },
  lsr: {
    model: "IOGP Multi-Label Transformer Classifier",
    supported_rules: 9,
    macro_f1: 0.91,
    micro_f1: 0.93,
    status: "HEALTHY",
  },
  clustering: {
    method: "HDBSCAN + SBERT Embeddings",
    cluster_count: 4,
    coherence_score_avg: 0.90,
    status: "HEALTHY",
  },
  llm: {
    status: "connected",
    provider: "Ollama (Sovereign Local)",
    configured_model: "mistral",
    active_memory_mb: 4120,
    quantization: "Q4_K_M",
    air_gapped: true,
  },
  data_drift: {
    "Equipment Vocabulary Drift": "0.02 (Minimal)",
    "Hazard Distribution Shift": "0.04 (Stable)",
    "pSIF Baseline Consistency": "99.1%",
  },
};
