import {
  DashboardSummary,
  ReportItem,
  ReportDetail,
  Barrier,
  Site,
  Activity,
  LSR,
  PrecursorCluster,
  AuditEntry,
  AlertItem,
  ModelHealth,
} from "./api";

export const FALLBACK_SITES: Site[] = [
  { id: "site-001", code: "MHN-OFFSHORE", name: "Mumbai High North Platform", location: "Western Offshore Basin, Maharashtra", operational_unit: "Offshore Production", risk_level: "HIGH" },
  { id: "site-002", code: "DGB-REFINERY", name: "Digboi Refinery Complex", location: "Tinsukia District, Assam", operational_unit: "Crude Distillation Unit (CDU-II)", risk_level: "CRITICAL" },
  { id: "site-003", code: "HZR-TERMINAL", name: "Hazira LNG Regasification Terminal", location: "Surat District, Gujarat", operational_unit: "Cryogenic Boil-off & Compression", risk_level: "HIGH" },
  { id: "site-004", code: "BMR-UPSTREAM", name: "Barmer Oil Gathering Station (OGS-3)", location: "Thar Basin, Rajasthan", operational_unit: "Enhanced Oil Recovery (Thermal/Polymer)", risk_level: "MEDIUM" },
  { id: "site-005", code: "PDC-PETROCHEM", name: "Paradip Petrochemicals & FCC Complex", location: "Jagatsinghpur, Odisha", operational_unit: "Fluidized Catalytic Cracking Unit", risk_level: "CRITICAL" },
];

export const FALLBACK_ACTIVITIES: Activity[] = [
  { id: "act-001", code: "HOT-WORK", name: "Hot Work & High-Energy Welding", category: "High Hazard", description: "Oxy-acetylene cutting, structural stick welding, and grinding near live process streams." },
  { id: "act-002", code: "CONFINED-SPACE", name: "Confined Space & Vessel Entry", category: "Critical", description: "Internal inspection and sludge cleaning in hydrocarbon storage bullets and distillation columns." },
  { id: "act-003", code: "ISOLATION-LOTO", name: "Positive Isolation & LOTO Blind Insertion", category: "Critical", description: "Double block and bleed verification and slip-blind bolting on high-pressure manifolds." },
  { id: "act-004", code: "HEAVY-LIFTING", name: "Offshore Crane Heavy Lift Operations", category: "Hazardous", description: "Supply boat cargo transfer and pedestal crane lifts over live subsea pipelines." },
  { id: "act-005", code: "HIGH-PRESSURE-PIGGING", name: "Pipeline Pigging & Receiver Operations", category: "High Hazard", description: "Intelligent pig receiver barrel depressurization and quick-opening door opening." },
];

export const FALLBACK_BARRIERS: Barrier[] = [
  { id: "bar-001", code: "BAR-ENG-01", name: "Positive Physical Isolation (Double Block & Bleed)", category: "Engineered", expected_function: "Zero energy state isolation via verified bleed point and mechanical blinds." },
  { id: "bar-002", code: "BAR-ENG-02", name: "Emergency Shutdown Valve (SDV/ESD Automation)", category: "Engineered", expected_function: "Automatic isolation of hydrocarbon inventories within 12 seconds of high-pressure trip." },
  { id: "bar-003", code: "BAR-ENG-03", name: "LEL Flammable & H2S Optical Gas Detectors", category: "Engineered", expected_function: "Continuous combustible gas perimeter monitoring with 2-out-of-3 voting logic." },
  { id: "bar-004", code: "BAR-ENG-04", name: "Pressure Safety Relief Valve (PSV) Discharge", category: "Engineered", expected_function: "Overpressure thermal relief routed safely to the high-pressure flare header." },
  { id: "bar-005", code: "BAR-ENG-05", name: "Deluge & Firewater Foam Suppression", category: "Engineered", expected_function: "High-rate area cooling and vapor cloud mitigation on manifold skid bays." },
  { id: "bar-006", code: "BAR-PROC-01", name: "Permit to Work (PTW) Simultaneous Operations Check", category: "Procedural", expected_function: "SIMOPS clash analysis and permit issuer physical site walk before ignition permit issuance." },
  { id: "bar-007", code: "BAR-PROC-02", name: "Lockout-Tagout (LOTO) & Key Interlock Protocol", category: "Procedural", expected_function: "Master lockbox custody verification preventing premature re-energization." },
  { id: "bar-008", code: "BAR-PROC-03", name: "Pre-Entry Gas Free Certification & Continuous Sniffing", category: "Procedural", expected_function: "Oxygen 20.9%, H2S < 5 ppm, LEL 0.0% validation every 60 minutes." },
  { id: "bar-009", code: "BAR-HUM-01", name: "Shift Fatigue Management & Maximum Work Hours", category: "Human", expected_function: "Strict 12-hour limit with mandatory 8-hour rest cycle during offshore turnaround." },
  { id: "bar-010", code: "BAR-HUM-02", name: "Dual Competency Sign-off for Critical Isolations", category: "Human", expected_function: "Independent peer verification of blind flange torque and slip spectacle plate orientation." },
];

export const FALLBACK_LSRS: LSR[] = [
  { id: "lsr-01", code: "LSR-01", name: "Bypassing Safety Controls", icon_name: "ShieldAlert", description: "Obtain authorization before overriding or disabling safety controls.", guidance: "Never bypass an ESD or interlock without MOC approval." },
  { id: "lsr-02", code: "LSR-02", name: "Confined Space Entry", icon_name: "DoorClosed", description: "Obtain authorization before entering a confined space.", guidance: "Verify atmosphere is gas-free and rescue plan is staged." },
  { id: "lsr-03", code: "LSR-03", name: "Energy Isolation", icon_name: "ZapOff", description: "Verify isolation and zero energy before beginning work.", guidance: "Always test before touch: try starting isolated equipment." },
  { id: "lsr-04", code: "LSR-04", name: "Hot Work Control", icon_name: "Flame", description: "Control flammables and ignition sources in hazardous zones.", guidance: "Continuous LEL monitoring required within 15 meters." },
  { id: "lsr-05", code: "LSR-05", name: "Line of Fire", icon_name: "Target", description: "Position yourself and others outside hazardous release zones.", guidance: "Never stand below suspended loads or near pressurized flanges." },
  { id: "lsr-06", code: "LSR-06", name: "Safe Mechanical Lifting", icon_name: "Anchor", description: "Plan lifting operations and control the area.", guidance: "Verify crane load charts and certified rigging hardware." },
  { id: "lsr-07", code: "LSR-07", name: "Work Authorization & PTW", icon_name: "FileCheck", description: "Work with a valid permit when required.", guidance: "Never commence work without verified gas tests and field walk." },
  { id: "lsr-08", code: "LSR-08", name: "Working at Height", icon_name: "ArrowUpRight", description: "Protect yourself against falling when working above 1.8 meters.", guidance: "100% tie-off with dual-lanyard shock-absorbing harness." },
  { id: "lsr-09", code: "LSR-09", name: "Toxic Gas Protection (H2S)", icon_name: "Skull", description: "Wear personal H2S detectors and know emergency escape routes.", guidance: "Immediately don EEBD mask upon first audible chirp." },
];

export const FALLBACK_REPORTS: ReportDetail[] = [
  {
    id: "rep-001",
    report_uid: "MHN-2026-0089",
    report_type: "Near-Miss Precursor",
    date_time: "2026-09-12 14:35:00",
    site_name: "Mumbai High North Platform",
    activity_name: "Valve Isolation & Maintenance",
    narrative_snippet: "During scheduled maintenance on Gas Lift Manifold GLM-04, contractor technician noted continuous weeping of pressurized hydrocarbon condensate from upstream block valve bonnet seal.",
    narrative: "During scheduled maintenance on Gas Lift Manifold GLM-04 at Mumbai High North, contractor technician noted continuous weeping of pressurized hydrocarbon condensate from upstream block valve bonnet seal. Flange bolts exhibited severe marine atmospheric corrosion. The line operates at 110 bar gas-lift injection pressure. Work was immediately suspended, double block and bleed integrity was re-inspected, and area was depopulated until emergency depressurization was completed via flare header.",
    equipment: "Gas Lift Manifold GLM-04 (110 Bar)",
    location: "Deck 2 Wellhead Area, Sector B",
    contractor_internal: "L&T Hydrocarbon Engineering",
    actual_outcome: "Minor condensate weepage onto drip tray, no ignition occurred.",
    potential_consequence: "Uncontrolled high-pressure gas blowout with jet fire risking platform evacuation.",
    psif_probability: 0.84,
    priority_score: 92,
    primary_barrier: "Positive Physical Isolation (Double Block & Bleed)",
    barrier_state: "FAILED",
    primary_lsr: "Energy Isolation (LSR-03)",
    review_status: "UNDER_INVESTIGATION",
    data_origin: "FIELD_LOG",
    entities: [
      { entity_type: "EQUIPMENT", value: "Gas Lift Manifold GLM-04", text_span: "Gas Lift Manifold GLM-04", confidence: 0.96 },
      { entity_type: "HAZARD", value: "110 bar gas-lift injection pressure", text_span: "110 bar gas-lift injection pressure", confidence: 0.94 },
      { entity_type: "CONDITION", value: "marine atmospheric corrosion", text_span: "marine atmospheric corrosion", confidence: 0.91 },
      { entity_type: "BARRIER", value: "double block and bleed", text_span: "double block and bleed", confidence: 0.95 },
    ],
    psif_prediction: {
      psif_probability: 0.84,
      priority_score: 92,
      confidence: 0.93,
      is_calibrated: true,
      primary_barrier: "Positive Physical Isolation (Double Block & Bleed)",
      barrier_state: "FAILED",
      credible_consequence: "High-pressure hydrocarbon blowout and potential vapor cloud explosion (VCE).",
      explanation_summary: "High operating pressure (110 bar) coupled with active valve packing failure in an offshore wellhead compartment creates severe SIF precursor potential.",
      shap_values: {
        "High Operating Pressure (>80 bar)": 0.38,
        "Barrier Degradation (DBB Bleed)": 0.29,
        "Corroded Marine Fasteners": 0.17,
        "Hot Work Proximity (SIMOPS)": 0.08,
      },
    },
    lsr_predictions: [
      { lsr_id: "lsr-03", code: "LSR-03", name: "Energy Isolation", confidence: 0.95, rank: 1 },
      { lsr_id: "lsr-01", code: "LSR-01", name: "Bypassing Safety Controls", confidence: 0.72, rank: 2 },
    ],
  },
  {
    id: "rep-002",
    report_uid: "DGB-2026-0014",
    report_type: "Hazard Observation",
    date_time: "2026-09-13 09:15:00",
    site_name: "Digboi Refinery Complex",
    activity_name: "Hot Work & High-Energy Welding",
    narrative_snippet: "Pre-hot-work gas sniffer test detected 18% LEL volatile hydrocarbons in drainage trench adjacent to Crude Distillation Column C-102 while structural welding was authorized 4 meters away.",
    narrative: "Pre-hot-work gas sniffer test detected 18% LEL volatile hydrocarbons in drainage trench adjacent to Crude Distillation Column C-102 at Digboi Refinery while structural welding was authorized 4 meters away. Fire watch was not equipped with continuous optical gas detector. Permit was recalled and sewer drain water-seal was replenished.",
    equipment: "Crude Distillation Column C-102 & Trench T-4",
    location: "CDU-II Process Battery Limit",
    contractor_internal: "Internal Maintenance Crew",
    actual_outcome: "Gas detected before ignition source applied.",
    potential_consequence: "Flash fire in open oily water sewer trench with personnel burn injuries.",
    psif_probability: 0.78,
    priority_score: 86,
    primary_barrier: "LEL Flammable & H2S Optical Gas Detectors",
    barrier_state: "DEGRADED",
    primary_lsr: "Hot Work Control (LSR-04)",
    review_status: "VERIFIED",
    data_origin: "FIELD_LOG",
    entities: [
      { entity_type: "EQUIPMENT", value: "Crude Distillation Column C-102", text_span: "Crude Distillation Column C-102", confidence: 0.94 },
      { entity_type: "HAZARD", value: "18% LEL volatile hydrocarbons", text_span: "18% LEL volatile hydrocarbons", confidence: 0.97 },
      { entity_type: "ACTIVITY", value: "structural welding", text_span: "structural welding", confidence: 0.92 },
    ],
    psif_prediction: {
      psif_probability: 0.78,
      priority_score: 86,
      confidence: 0.89,
      is_calibrated: true,
      primary_barrier: "LEL Flammable & H2S Optical Gas Detectors",
      barrier_state: "DEGRADED",
      credible_consequence: "Trench flash fire propagating to crude pre-heat exchanger train.",
      shap_values: {
        "Flammable Vapor (>10% LEL)": 0.44,
        "Active Hot Work Spark Source": 0.26,
        "Inadequate Fire Watch Sniffing": 0.18,
      },
    },
    lsr_predictions: [
      { lsr_id: "lsr-04", code: "LSR-04", name: "Hot Work Control", confidence: 0.94, rank: 1 },
      { lsr_id: "lsr-07", code: "LSR-07", name: "Work Authorization & PTW", confidence: 0.81, rank: 2 },
    ],
  },
  {
    id: "rep-003",
    report_uid: "HZR-2026-0052",
    report_type: "Equipment Failure",
    date_time: "2026-09-14 11:40:00",
    site_name: "Hazira LNG Regasification Terminal",
    activity_name: "High-Pressure Pipeline Pigging",
    narrative_snippet: "BOG (Boil-off Gas) Compressor K-201B dry gas seal secondary vent pressure tripped alarm at 3.8 bar. Manual bypass had been enabled during instrument calibration without MOC authorization.",
    narrative: "BOG (Boil-off Gas) Compressor K-201B dry gas seal secondary vent pressure tripped alarm at 3.8 bar. Manual bypass of the ESD trip interlock had been enabled during instrument calibration earlier that morning without MOC authorization. Flare knock-out drum level was elevated.",
    equipment: "BOG Compressor K-201B (Elliott Cryogenic)",
    location: "Compression Shed Bay 3",
    contractor_internal: "Siemens Energy Service",
    actual_outcome: "Compressor manually tripped by console supervisor after 6 minutes.",
    potential_consequence: "Dry gas seal blowout resulting in major cryogenic methane vapor cloud release.",
    psif_probability: 0.91,
    priority_score: 96,
    primary_barrier: "Emergency Shutdown Valve (SDV/ESD Automation)",
    barrier_state: "FAILED",
    primary_lsr: "Bypassing Safety Controls (LSR-01)",
    review_status: "VERIFIED",
    data_origin: "SCADA_ALARM",
    entities: [
      { entity_type: "EQUIPMENT", value: "BOG Compressor K-201B", text_span: "BOG Compressor K-201B", confidence: 0.98 },
      { entity_type: "HAZARD", value: "secondary vent pressure 3.8 bar", text_span: "secondary vent pressure", confidence: 0.91 },
      { entity_type: "VIOLATION", value: "Manual bypass without MOC", text_span: "Manual bypass", confidence: 0.95 },
    ],
    psif_prediction: {
      psif_probability: 0.91,
      priority_score: 96,
      confidence: 0.96,
      is_calibrated: true,
      primary_barrier: "Emergency Shutdown Valve (SDV/ESD Automation)",
      barrier_state: "FAILED",
      credible_consequence: "Catastrophic cryogenic seal rupture and unconfined vapor cloud explosion.",
      shap_values: {
        "Defeated Safety Interlock (Bypass)": 0.48,
        "Cryogenic Gas Inventory": 0.28,
        "Unattended Calibration Mode": 0.15,
      },
    },
    lsr_predictions: [
      { lsr_id: "lsr-01", code: "LSR-01", name: "Bypassing Safety Controls", confidence: 0.98, rank: 1 },
      { lsr_id: "lsr-03", code: "LSR-03", name: "Energy Isolation", confidence: 0.76, rank: 2 },
    ],
  },
  {
    id: "rep-004",
    report_uid: "BMR-2026-0031",
    report_type: "Near-Miss Precursor",
    date_time: "2026-09-14 16:10:00",
    site_name: "Barmer Oil Gathering Station (OGS-3)",
    activity_name: "Positive Isolation & LOTO Blind Insertion",
    narrative_snippet: "During crude oil transfer line tie-in, pipefitter found slip blind installed backwards with open spacer exposed to active pressure line due to worn marking paint on spectacle blind.",
    narrative: "During crude oil transfer line tie-in at Barmer OGS-3, pipefitter found slip blind installed backwards with open spacer exposed to active pressure line due to worn marking paint on spectacle blind. Line was pressurized to 45 bar with heated waxy crude (75°C).",
    equipment: "Spectacle Blind SB-14A & Trunkline TL-02",
    location: "Manifold Skid East",
    contractor_internal: "Punj Lloyd Infrastructure",
    actual_outcome: "Discovered during walkdown prior to valve crack opening.",
    potential_consequence: "Hot waxy crude spray at 45 bar causing severe thermal burns and pool fire.",
    psif_probability: 0.72,
    priority_score: 81,
    primary_barrier: "Dual Competency Sign-off for Critical Isolations",
    barrier_state: "DEGRADED",
    primary_lsr: "Energy Isolation (LSR-03)",
    review_status: "VERIFIED",
    data_origin: "FIELD_LOG",
    entities: [
      { entity_type: "EQUIPMENT", value: "Spectacle Blind SB-14A", text_span: "Spectacle Blind SB-14A", confidence: 0.95 },
      { entity_type: "HAZARD", value: "45 bar heated waxy crude 75°C", text_span: "45 bar heated waxy crude", confidence: 0.94 },
    ],
    psif_prediction: {
      psif_probability: 0.72,
      priority_score: 81,
      confidence: 0.91,
      is_calibrated: true,
      primary_barrier: "Dual Competency Sign-off for Critical Isolations",
      barrier_state: "DEGRADED",
      shap_values: {
        "Heated Pressurized Fluid": 0.36,
        "Human Error (Inverted Blind)": 0.32,
        "Sign-off Process Gap": 0.14,
      },
    },
    lsr_predictions: [
      { lsr_id: "lsr-03", code: "LSR-03", name: "Energy Isolation", confidence: 0.92, rank: 1 },
    ],
  },
  {
    id: "rep-005",
    report_uid: "PDC-2026-0077",
    report_type: "Hazard Observation",
    date_time: "2026-09-15 08:20:00",
    site_name: "Paradip Petrochemicals & FCC Complex",
    activity_name: "Confined Space & Vessel Entry",
    narrative_snippet: "Entry attendants noted standby breathing air bottle manifold pressure dropping intermittently from 200 bar to 40 bar during reactor vessel R-301 catalyst bed inspection.",
    narrative: "Entry attendants noted standby breathing air bottle manifold pressure dropping intermittently from 200 bar to 40 bar during reactor vessel R-301 catalyst bed inspection at Paradip FCC. Air supply regulator had loose quick-connect coupling. Two entrants inside nitrogen-inerted atmosphere were evacuated immediately.",
    equipment: "Breathing Air Manifold BAM-02 & Reactor R-301",
    location: "FCC Reactor Structure Level 4",
    contractor_internal: "Technip Energies Contracting",
    actual_outcome: "Entrants safely egressed within 90 seconds without hypoxia symptoms.",
    potential_consequence: "Nitrogen asphyxiation inside confined catalyst reactor resulting in multiple fatalities.",
    psif_probability: 0.94,
    priority_score: 98,
    primary_barrier: "Pre-Entry Gas Free Certification & Continuous Sniffing",
    barrier_state: "FAILED",
    primary_lsr: "Confined Space Entry (LSR-02)",
    review_status: "UNDER_INVESTIGATION",
    data_origin: "FIELD_LOG",
    entities: [
      { entity_type: "EQUIPMENT", value: "Breathing Air Manifold BAM-02", text_span: "Breathing Air Manifold BAM-02", confidence: 0.97 },
      { entity_type: "HAZARD", value: "nitrogen-inerted atmosphere", text_span: "nitrogen-inerted atmosphere", confidence: 0.98 },
    ],
    psif_prediction: {
      psif_probability: 0.94,
      priority_score: 98,
      confidence: 0.97,
      is_calibrated: true,
      primary_barrier: "Pre-Entry Gas Free Certification & Continuous Sniffing",
      barrier_state: "FAILED",
      credible_consequence: "Immediate nitrogen asphyxiation (zero oxygen survival < 3 minutes).",
      shap_values: {
        "IDLH Inert Atmosphere (N2)": 0.52,
        "Life-Support Air System Degradation": 0.34,
        "Confined Space Geometry": 0.12,
      },
    },
    lsr_predictions: [
      { lsr_id: "lsr-02", code: "LSR-02", name: "Confined Space Entry", confidence: 0.99, rank: 1 },
    ],
  },
  {
    id: "rep-006",
    report_uid: "MHN-2026-0095",
    report_type: "Near-Miss Precursor",
    date_time: "2026-09-11 11:20:00",
    site_name: "Mumbai High North Platform",
    activity_name: "Heavy Lift & Rigging Operations",
    narrative_snippet: "Auxiliary hoist wire rope on offshore crane PC-01 showed 3 broken outer wire strands during pre-use load test with 8-ton subsea manifold bundle suspended over active production headers.",
    narrative: "Auxiliary hoist wire rope on offshore pedestal crane PC-01 showed 3 broken outer wire strands adjacent to the equalizer sheave during pre-use load test with 8-ton subsea manifold bundle suspended over active production headers. Wind gust was 28 knots. Lift supervisor halted operation and ordered load lowered to supply vessel deck.",
    equipment: "Offshore Pedestal Crane PC-01 Auxiliary Winch",
    location: "South Main Deck Crane Bay",
    contractor_internal: "L&T Heavy Engineering",
    actual_outcome: "Lift suspended, load landed safely on deck.",
    potential_consequence: "Catastrophic dropped object onto pressurized hydrocarbon headers leading to massive explosion.",
    psif_probability: 0.89,
    priority_score: 94,
    primary_barrier: "Certified Rigging Gear & Lift Plan Authorization",
    barrier_state: "FAILED",
    primary_lsr: "Safe Mechanical Lifting (LSR-05)",
    review_status: "VERIFIED",
    data_origin: "FIELD_LOG",
    entities: [
      { entity_type: "EQUIPMENT", value: "Pedestal Crane PC-01", text_span: "Pedestal Crane PC-01", confidence: 0.96 },
      { entity_type: "HAZARD", value: "broken outer wire strands", text_span: "broken outer wire strands", confidence: 0.94 },
    ],
    psif_prediction: {
      psif_probability: 0.89,
      priority_score: 94,
      confidence: 0.93,
      is_calibrated: true,
      primary_barrier: "Certified Rigging Gear & Lift Plan Authorization",
      barrier_state: "FAILED",
      credible_consequence: "High-energy impact rupture of live wellhead flowlines.",
      shap_values: { "Dropped Object Energy": 0.44, "Corrosion Fatigue": 0.28, "SIMOPS Proximity": 0.16 },
    },
    lsr_predictions: [{ lsr_id: "lsr-05", code: "LSR-05", name: "Safe Mechanical Lifting", confidence: 0.96, rank: 1 }],
  },
  {
    id: "rep-007",
    report_uid: "HZR-2026-0061",
    report_type: "Near-Miss Precursor",
    date_time: "2026-09-10 16:45:00",
    site_name: "Hazira LNG Regasification Terminal",
    activity_name: "Cryogenic LNG Transfer & Unloading",
    narrative_snippet: "Optical infrared gas detectors alarmed at 12% LEL at cryogenic swivel joint of Marine Unloading Arm MLA-02 during carrier discharge at Jetty 2.",
    narrative: "During LNG carrier discharge at Jetty 2, optical infrared gas detectors alarmed at 12% LEL at the cryogenic swivel joint of Marine Unloading Arm MLA-02. Frosting was noted on the liquid nitrogen barrier gland seal. Emergency discharge stop was activated and nitrogen purge initiated.",
    equipment: "Marine Unloading Arm MLA-02 Cryogenic Swivel",
    location: "Marine Jetty 2 Unloading Berth",
    contractor_internal: "FMC Technologies Service",
    actual_outcome: "Emergency shutdown tripped, liquid inventory isolated in 8 seconds.",
    potential_consequence: "Massive cryogenic methane liquid spill at 4000 m3/hr vaporizing into jetty flash fire.",
    psif_probability: 0.92,
    priority_score: 97,
    primary_barrier: "Emergency Shutdown Valve (SDV/ESD Automation)",
    barrier_state: "VERIFIED",
    primary_lsr: "Work Authorization & PTW (LSR-07)",
    review_status: "VERIFIED",
    data_origin: "SCADA_ALARM",
    entities: [
      { entity_type: "EQUIPMENT", value: "Unloading Arm MLA-02", text_span: "Unloading Arm MLA-02", confidence: 0.98 },
      { entity_type: "HAZARD", value: "12% LEL cryogenic methane", text_span: "12% LEL", confidence: 0.95 },
    ],
    psif_prediction: {
      psif_probability: 0.92,
      priority_score: 97,
      confidence: 0.95,
      is_calibrated: true,
      primary_barrier: "Emergency Shutdown Valve (SDV/ESD Automation)",
      barrier_state: "VERIFIED",
      credible_consequence: "Unconfined vapor cloud explosion over marine loading terminal.",
      shap_values: { "Cryogenic Flow Rate": 0.49, "Marine Terminal Proximity": 0.29, "Sensor Latency": 0.11 },
    },
    lsr_predictions: [{ lsr_id: "lsr-07", code: "LSR-07", name: "Work Authorization & PTW", confidence: 0.94, rank: 1 }],
  },
  {
    id: "rep-008",
    report_uid: "DGB-2026-0022",
    report_type: "Hazard Observation",
    date_time: "2026-09-09 14:10:00",
    site_name: "Digboi Refinery Complex",
    activity_name: "High-Pressure Hydrogen Reforming",
    narrative_snippet: "Ultrasonic acoustic sensor identified high-pressure micro-jet hydrogen leak from RTJ gasket flange on compressor C-302 discharge header at 68 bar.",
    narrative: "Routine ultrasonic leak detection identified a micro-jet of hydrogen leaking from the RTJ gasket flange of compressor C-302 at 68 bar. Invisible hydrogen flame check performed with thermal camera showed no ignition. Compressor was transitioned to standby train and line depressured to fuel gas system.",
    equipment: "Hydrogen Booster Compressor C-302 Discharge Flange",
    location: "Hydrotreater Compressor House Bay 1",
    contractor_internal: "Internal Maintenance Crew",
    actual_outcome: "Depressured safely with nitrogen purge, no ignition.",
    potential_consequence: "Invisible high-temperature hydrogen torch fire impinging on neighboring solvent drums.",
    psif_probability: 0.86,
    priority_score: 90,
    primary_barrier: "Positive Physical Isolation (Double Block & Bleed)",
    barrier_state: "DEGRADED",
    primary_lsr: "Energy Isolation (LSR-03)",
    review_status: "UNDER_INVESTIGATION",
    data_origin: "FIELD_LOG",
    entities: [
      { entity_type: "EQUIPMENT", value: "Compressor C-302", text_span: "Compressor C-302", confidence: 0.97 },
      { entity_type: "HAZARD", value: "68 bar hydrogen micro-jet", text_span: "68 bar hydrogen", confidence: 0.96 },
    ],
    psif_prediction: {
      psif_probability: 0.86,
      priority_score: 90,
      confidence: 0.92,
      is_calibrated: true,
      primary_barrier: "Positive Physical Isolation (Double Block & Bleed)",
      barrier_state: "DEGRADED",
      credible_consequence: "Invisible hydrogen jet fire and BLEVE of adjacent surge vessel.",
      shap_values: { "Hydrogen Volatility": 0.46, "Operating Pressure (68 bar)": 0.32, "Confined Building": 0.12 },
    },
    lsr_predictions: [{ lsr_id: "lsr-03", code: "LSR-03", name: "Energy Isolation", confidence: 0.93, rank: 1 }],
  },
  {
    id: "rep-009",
    report_uid: "BMR-2026-0039",
    report_type: "Equipment Failure",
    date_time: "2026-09-08 10:30:00",
    site_name: "Barmer Oil Gathering Station (OGS-3)",
    activity_name: "Pig Receiver Operations & Trap Opening",
    narrative_snippet: "Trapped pressure behind Pig Receiver PR-01 quick-opening door blew waxy crude mist through safety bleeder screw when opened; pressure transmitter read 0 bar due to wax plug.",
    narrative: "Operator attempted to unlock quick-opening closure door of Pig Receiver PR-01 while the barrel pressure gauge read zero. When the safety interlock bleeder screw was backed out, a high-velocity jet of pressurized waxy crude and trapped casinghead gas discharged through the bleed port. The primary pressure transmitter had wax blockage.",
    equipment: "Pig Receiver Barrel PR-01 Quick-Opening Closure",
    location: "Trunkline Pigging Skid East",
    contractor_internal: "Cairn E&P Operations",
    actual_outcome: "Safety bleed port prevented full door blowout; operator unhurt behind barrier shield.",
    potential_consequence: "Full closure door blowout under 25 bar residual pressure striking operators fatally.",
    psif_probability: 0.88,
    priority_score: 93,
    primary_barrier: "Mechanical Interlocks & Car-Seals",
    barrier_state: "FAILED",
    primary_lsr: "Bypassing Safety Controls (LSR-01)",
    review_status: "VERIFIED",
    data_origin: "FIELD_LOG",
    entities: [
      { entity_type: "EQUIPMENT", value: "Pig Receiver PR-01", text_span: "Pig Receiver PR-01", confidence: 0.97 },
      { entity_type: "HAZARD", value: "trapped casinghead gas 25 bar", text_span: "trapped casinghead gas", confidence: 0.94 },
    ],
    psif_prediction: {
      psif_probability: 0.88,
      priority_score: 93,
      confidence: 0.94,
      is_calibrated: true,
      primary_barrier: "Mechanical Interlocks & Car-Seals",
      barrier_state: "FAILED",
      credible_consequence: "Missile projectile door release and high-pressure crude blowout.",
      shap_values: { "Trapped Mechanical Energy": 0.43, "Wax Sensor Failure": 0.33, "Interlock Bypass": 0.17 },
    },
    lsr_predictions: [{ lsr_id: "lsr-01", code: "LSR-01", name: "Bypassing Safety Controls", confidence: 0.95, rank: 1 }],
  },
  {
    id: "rep-010",
    report_uid: "PDC-2026-0082",
    report_type: "Near-Miss Precursor",
    date_time: "2026-09-07 13:00:00",
    site_name: "Paradip Petrochemicals & FCC Complex",
    activity_name: "Hot Work & High-Energy Welding",
    narrative_snippet: "Contractor struck arc on reboiler E-204 shell before atmospheric test was signed off; personal 4-gas sniffer immediately alarmed at 14% LEL from reflux drain pinhole.",
    narrative: "Contractor welder struck an arc on the shell of reboiler E-204 before the fire watch had completed flammable vapor sniffing. The portable 4-gas detector on the welder's harness immediately alarmed at 14% LEL due to a pinhole vapor leak from the nearby condensator reflux drum drain valve. Welding halted immediately.",
    equipment: "Propylene Splitter Reboiler E-204 Shell",
    location: "Petrochemical Fractionation Unit Level 2",
    contractor_internal: "Punj Lloyd Construction",
    actual_outcome: "Arc extinguished within 1 second; LEL levels dissipated with steam horn.",
    potential_consequence: "Ignition of propylene vapor cloud in congested structural module causing severe blast overpressure.",
    psif_probability: 0.83,
    priority_score: 89,
    primary_barrier: "LEL Flammable & H2S Optical Gas Detectors",
    barrier_state: "DEGRADED",
    primary_lsr: "Hot Work Control (LSR-04)",
    review_status: "PENDING",
    data_origin: "FIELD_LOG",
    entities: [
      { entity_type: "EQUIPMENT", value: "Reboiler E-204", text_span: "Reboiler E-204", confidence: 0.95 },
      { entity_type: "HAZARD", value: "14% LEL propylene vapor", text_span: "14% LEL propylene", confidence: 0.96 },
    ],
    psif_prediction: {
      psif_probability: 0.83,
      priority_score: 89,
      confidence: 0.91,
      is_calibrated: true,
      primary_barrier: "LEL Flammable & H2S Optical Gas Detectors",
      barrier_state: "DEGRADED",
      credible_consequence: "Congested vapor cloud explosion (VCE) in olefin fractionation plant.",
      shap_values: { "Flammable Gas Proximity": 0.45, "Active Hot Work Ignition": 0.31, "PTW Verification Gap": 0.16 },
    },
    lsr_predictions: [{ lsr_id: "lsr-04", code: "LSR-04", name: "Hot Work Control", confidence: 0.96, rank: 1 }],
  },
  {
    id: "rep-011",
    report_uid: "MHN-2026-0102",
    report_type: "Near-Miss Precursor",
    date_time: "2026-09-06 09:40:00",
    site_name: "Mumbai High North Platform",
    activity_name: "Offshore Helideck Aviation Logistics",
    narrative_snippet: "Static bonding ground reel clamp found with sheared spring tension during Sikorsky S-92 hot-refueling preparation with 14 personnel aboard.",
    narrative: "Aviation refueler discovered static bonding reel clamp had sheared spring tension during Sikorsky S-92 helicopter hot-refueling preparation. Helicopter blades were rotating with 14 passengers on board. Refueling was cancelled until grounding cable was continuity-tested to deck steel (< 10 ohms).",
    equipment: "Helideck Jet A-1 Fueling Skid Grounding Reel",
    location: "Main Helideck Aviation Fuel Station",
    contractor_internal: "Pawan Hans Offshore Aviation",
    actual_outcome: "Hot refueling aborted; cold refueling executed after continuity verified.",
    potential_consequence: "Electrostatic spark ignition during 300 gpm aviation turbine fuel transfer under rotor wash.",
    psif_probability: 0.79,
    priority_score: 84,
    primary_barrier: "Hazardous Area Ex-Rated Electrical Equipment",
    barrier_state: "FAILED",
    primary_lsr: "Bypassing Safety Controls (LSR-01)",
    review_status: "VERIFIED",
    data_origin: "FIELD_LOG",
    entities: [
      { entity_type: "EQUIPMENT", value: "Jet A-1 Fueling Skid", text_span: "Jet A-1 Fueling Skid", confidence: 0.97 },
      { entity_type: "HAZARD", value: "Static bonding clamp shear", text_span: "Static bonding clamp", confidence: 0.93 },
    ],
    psif_prediction: {
      psif_probability: 0.79,
      priority_score: 84,
      confidence: 0.89,
      is_calibrated: true,
      primary_barrier: "Hazardous Area Ex-Rated Electrical Equipment",
      barrier_state: "FAILED",
      credible_consequence: "Aviation fuel fire engulfing passenger helicopter on offshore helideck.",
      shap_values: { "Fuel Flashpoint Risk": 0.40, "Rotating Rotor Downwash": 0.32, "Grounding Fault": 0.20 },
    },
    lsr_predictions: [{ lsr_id: "lsr-01", code: "LSR-01", name: "Bypassing Safety Controls", confidence: 0.91, rank: 1 }],
  },
  {
    id: "rep-012",
    report_uid: "DGB-2026-0029",
    report_type: "Near-Miss Precursor",
    date_time: "2026-09-05 15:30:00",
    site_name: "Digboi Refinery Complex",
    activity_name: "Electrical Isolation & Motor Control Center Maintenance",
    narrative_snippet: "6.6 kV vacuum circuit breaker CB-08 automatic busbar shutters jammed open during racking out; padlocks mistakenly placed on adjacent feeder due to degraded tag.",
    narrative: "Electrician assigned to rack out 6.6 kV vacuum circuit breaker CB-08 noticed busbar shutter mechanism jammed in open position with live busbar spouts partially visible. Lockout padlocks were applied to adjacent cubicle in error due to faded equipment labels. Work was stopped and LOTO audit executed.",
    equipment: "6.6 kV Switchgear Cubicle CB-08 Busbar Shutter",
    location: "Main Electrical Substation 2",
    contractor_internal: "ABB Power Grid Services",
    actual_outcome: "Electrician halted before inserting grounding truck; zero flashover.",
    potential_consequence: "6.6 kV phase-to-phase arc flash explosion causing fatal thermal blast trauma.",
    psif_probability: 0.90,
    priority_score: 95,
    primary_barrier: "Energy Isolation Lockout/Tagout (LOTO)",
    barrier_state: "FAILED",
    primary_lsr: "Energy Isolation (LSR-03)",
    review_status: "VERIFIED",
    data_origin: "FIELD_LOG",
    entities: [
      { entity_type: "EQUIPMENT", value: "6.6 kV Switchgear CB-08", text_span: "6.6 kV Switchgear CB-08", confidence: 0.98 },
      { entity_type: "HAZARD", value: "live 6.6 kV busbars exposed", text_span: "live busbar spouts", confidence: 0.95 },
    ],
    psif_prediction: {
      psif_probability: 0.90,
      priority_score: 95,
      confidence: 0.96,
      is_calibrated: true,
      primary_barrier: "Energy Isolation Lockout/Tagout (LOTO)",
      barrier_state: "FAILED",
      credible_consequence: "Catastrophic arc blast exceeding 40 cal/cm2 within enclosed switchgear room.",
      shap_values: { "High Voltage Energy (6.6 kV)": 0.47, "Shutter Jamming Defect": 0.31, "Label Misidentification": 0.17 },
    },
    lsr_predictions: [{ lsr_id: "lsr-03", code: "LSR-03", name: "Energy Isolation", confidence: 0.97, rank: 1 }],
  },
  {
    id: "rep-013",
    report_uid: "HZR-2026-0070",
    report_type: "Equipment Failure",
    date_time: "2026-09-04 11:15:00",
    site_name: "Hazira LNG Regasification Terminal",
    activity_name: "High-Pressure Gas Compressor Maintenance",
    narrative_snippet: "Emergency sectionalizing valve MOV-104 failed to close during quarterly ESD loop simulation; limit switch stuck due to marine salt encrustation.",
    narrative: "Motor-operated valve MOV-104 failed to close on remote command during routine ESD loop test. Actuator limit switch was stuck due to salt deposit buildup. High-pressure sendout header operates at 92 bar feeding the National Gas Grid.",
    equipment: "National Gas Grid Sendout MOV-104 (92 Bar)",
    location: "High Pressure Sendout Metering Station",
    contractor_internal: "Rotork Actuator Service",
    actual_outcome: "Manual handwheel applied to seat valve; limit switch cleaned and re-calibrated.",
    potential_consequence: "Failure to isolate 92 bar natural gas trunkline in the event of rupture.",
    psif_probability: 0.81,
    priority_score: 87,
    primary_barrier: "Emergency Shutdown Valve (SDV/ESD Automation)",
    barrier_state: "DEGRADED",
    primary_lsr: "Work Authorization & PTW (LSR-07)",
    review_status: "VERIFIED",
    data_origin: "SCADA_ALARM",
    entities: [
      { entity_type: "EQUIPMENT", value: "Sendout Valve MOV-104", text_span: "Sendout Valve MOV-104", confidence: 0.96 },
      { entity_type: "HAZARD", value: "92 bar natural gas header", text_span: "92 bar", confidence: 0.92 },
    ],
    psif_prediction: {
      psif_probability: 0.81,
      priority_score: 87,
      confidence: 0.90,
      is_calibrated: true,
      primary_barrier: "Emergency Shutdown Valve (SDV/ESD Automation)",
      barrier_state: "DEGRADED",
      credible_consequence: "Uncontainable high-pressure pipeline blowout propagating to regional grid.",
      shap_values: { "Trunkline Pressure (92 bar)": 0.42, "Actuator Failure": 0.34, "Marine Environment": 0.15 },
    },
    lsr_predictions: [{ lsr_id: "lsr-07", code: "LSR-07", name: "Work Authorization & PTW", confidence: 0.91, rank: 1 }],
  },
  {
    id: "rep-014",
    report_uid: "BMR-2026-0044",
    report_type: "Near-Miss Precursor",
    date_time: "2026-09-03 14:40:00",
    site_name: "Barmer Oil Gathering Station (OGS-3)",
    activity_name: "Confined Space & Vessel Entry",
    narrative_snippet: "Multi-gas personal detector alarmed for 15 ppm H2S inside separator FWKO-02; entrant egress temporarily impeded by snagged retrieval lifeline in sludge.",
    narrative: "During internal washdown of FWKO-02, continuous personal multi-gas detector alarmed for toxic H2S at 15 ppm inside the vessel. Entrant's egress was momentarily delayed due to tangled retrieval harness. Standby attendant activated evacuation air horn and assisted egress. Sludge off-gassing under high ambient desert temperature (44°C).",
    equipment: "Free Water Knockout Vessel FWKO-02 Internals",
    location: "Crude Separation Train B",
    contractor_internal: "Halliburton Energy Services",
    actual_outcome: "Entrant extracted safely within 45 seconds; continuous ventilation upgraded.",
    potential_consequence: "Acute toxic hydrogen sulfide gas collapse and chemical asphyxiation.",
    psif_probability: 0.87,
    priority_score: 91,
    primary_barrier: "Pre-Entry Gas Free Certification & Continuous Sniffing",
    barrier_state: "DEGRADED",
    primary_lsr: "Confined Space Entry (LSR-02)",
    review_status: "VERIFIED",
    data_origin: "FIELD_LOG",
    entities: [
      { entity_type: "EQUIPMENT", value: "Separator FWKO-02", text_span: "Separator FWKO-02", confidence: 0.97 },
      { entity_type: "HAZARD", value: "15 ppm toxic H2S off-gassing", text_span: "15 ppm toxic H2S", confidence: 0.98 },
    ],
    psif_prediction: {
      psif_probability: 0.87,
      priority_score: 91,
      confidence: 0.94,
      is_calibrated: true,
      primary_barrier: "Pre-Entry Gas Free Certification & Continuous Sniffing",
      barrier_state: "DEGRADED",
      credible_consequence: "Loss of consciousness and fatal toxic H2S inhalation in enclosed space.",
      shap_values: { "Toxic Gas Concentration": 0.48, "Entangled Lifeline": 0.31, "Extreme Ambient Heat": 0.14 },
    },
    lsr_predictions: [{ lsr_id: "lsr-02", code: "LSR-02", name: "Confined Space Entry", confidence: 0.98, rank: 1 }],
  },
  {
    id: "rep-015",
    report_uid: "PDC-2026-0091",
    report_type: "Hazard Observation",
    date_time: "2026-09-02 16:15:00",
    site_name: "Paradip Petrochemicals & FCC Complex",
    activity_name: "Pipeline Hydrotesting & Pressure Testing",
    narrative_snippet: "Pneumatic leak test reached 18 bar when inspection revealed cast-iron butterfly valve rated only for 10 bar installed in test manifold.",
    narrative: "During pneumatic leak test prior to hydrotest, test pressure reached 18 bar when contractor supervisor noticed an unrated cast iron butterfly valve installed in the test manifold rated only for 10 bar. Testing halted and pressure depressurized via calibrated throttle needle valve.",
    equipment: "Heavy Naphtha Transfer Line NL-04 Test Manifold",
    location: "Offsite Storage Tank Farm Skid",
    contractor_internal: "Simon India EPC",
    actual_outcome: "Overpressure identified before brittle fracture; assembly re-rigged with forged steel.",
    potential_consequence: "Catastrophic shrapnel fragmentation blast under pneumatic test gas expansion.",
    psif_probability: 0.85,
    priority_score: 91,
    primary_barrier: "Permit to Work (PTW) System Authorization",
    barrier_state: "FAILED",
    primary_lsr: "Work Authorization & PTW (LSR-07)",
    review_status: "VERIFIED",
    data_origin: "FIELD_LOG",
    entities: [
      { entity_type: "EQUIPMENT", value: "Transfer Line NL-04", text_span: "Transfer Line NL-04", confidence: 0.95 },
      { entity_type: "HAZARD", value: "18 bar pneumatic pressure in 10 bar valve", text_span: "18 bar pneumatic pressure", confidence: 0.96 },
    ],
    psif_prediction: {
      psif_probability: 0.85,
      priority_score: 91,
      confidence: 0.92,
      is_calibrated: true,
      primary_barrier: "Permit to Work (PTW) System Authorization",
      barrier_state: "FAILED",
      credible_consequence: "Brittle metal shrapnel burst striking testing technicians.",
      shap_values: { "Pneumatic Stored Energy": 0.46, "Under-rated Metallurgy": 0.34, "Barricade Distance Gap": 0.12 },
    },
    lsr_predictions: [{ lsr_id: "lsr-07", code: "LSR-07", name: "Work Authorization & PTW", confidence: 0.95, rank: 1 }],
  },
  {
    id: "rep-016",
    report_uid: "MHN-2026-0110",
    report_type: "Near-Miss Precursor",
    date_time: "2026-09-01 10:20:00",
    site_name: "Mumbai High North Platform",
    activity_name: "Well Workover & Wireline Logging",
    narrative_snippet: "Wireline lubricator packing nut backed off under 95 bar surge pressure during logging tool retrieval on Wellhead MHN-12.",
    narrative: "Wireline lubricator packing nut loosened under surge pressure of 95 bar during tool retrieval. Small oil and gas plume released toward cellar deck before hydraulic stuffing box pack-off was actuated from remote console.",
    equipment: "Wellhead Christmas Tree MHN-12 Lubricator Assembly",
    location: "Cellar Deck Wellbay Slot 14",
    contractor_internal: "Schlumberger Wireline",
    actual_outcome: "Remote hydraulic pack-off shut in well within 4 seconds.",
    potential_consequence: "Full wireline blowout and hydrocarbon jet flame across offshore wellbay.",
    psif_probability: 0.82,
    priority_score: 88,
    primary_barrier: "Positive Physical Isolation (Double Block & Bleed)",
    barrier_state: "DEGRADED",
    primary_lsr: "Line of Fire & Stored Energy (LSR-06)",
    review_status: "UNDER_INVESTIGATION",
    data_origin: "FIELD_LOG",
    entities: [
      { entity_type: "EQUIPMENT", value: "Wellhead MHN-12 Lubricator", text_span: "Wellhead MHN-12 Lubricator", confidence: 0.97 },
      { entity_type: "HAZARD", value: "95 bar hydrocarbon surge pressure", text_span: "95 bar surge pressure", confidence: 0.94 },
    ],
    psif_prediction: {
      psif_probability: 0.82,
      priority_score: 88,
      confidence: 0.90,
      is_calibrated: true,
      primary_barrier: "Positive Physical Isolation (Double Block & Bleed)",
      barrier_state: "DEGRADED",
      credible_consequence: "Uncontrolled wellhead blowout and offshore fire.",
      shap_values: { "Wellbore Surge Pressure": 0.43, "Mechanical Thread Backoff": 0.32, "Confined Cellar Deck": 0.17 },
    },
    lsr_predictions: [{ lsr_id: "lsr-06", code: "LSR-06", name: "Line of Fire & Stored Energy", confidence: 0.93, rank: 1 }],
  },
  {
    id: "rep-017",
    report_uid: "DGB-2026-0035",
    report_type: "Equipment Failure",
    date_time: "2026-08-30 08:50:00",
    site_name: "Digboi Refinery Complex",
    activity_name: "Chemical Dosing & Caustic Neutralization",
    narrative_snippet: "Corrosive 50% sodium hydroxide solution sprayed through ruptured pump diaphragm; dosing check valve failed backward under 18 bar crude line pressure.",
    narrative: "Corrosive 50% sodium hydroxide solution sprayed through ruptured PTFE diaphragm onto splash shield. Dosing line check valve had failed backward, exposing low-pressure dosing pump to crude charge line backpressure of 18 bar. Operator wearing full face shield and chemical apron escaped uninjured.",
    equipment: "Caustic Injection Pump P-402A Diaphragm Head",
    location: "Desalter Unit Dosing Skid",
    contractor_internal: "Internal Maintenance Crew",
    actual_outcome: "Splash shield contained liquid; emergency eye wash activated.",
    potential_consequence: "High-pressure chemical caustic spray causing catastrophic blinding injuries and skin necrosis.",
    psif_probability: 0.74,
    priority_score: 79,
    primary_barrier: "Management of Change (MOC) Risk Assessment",
    barrier_state: "FAILED",
    primary_lsr: "Line of Fire & Stored Energy (LSR-06)",
    review_status: "VERIFIED",
    data_origin: "FIELD_LOG",
    entities: [
      { entity_type: "EQUIPMENT", value: "Caustic Pump P-402A", text_span: "Caustic Pump P-402A", confidence: 0.96 },
      { entity_type: "HAZARD", value: "50% caustic soda at 18 bar", text_span: "50% sodium hydroxide", confidence: 0.97 },
    ],
    psif_prediction: {
      psif_probability: 0.74,
      priority_score: 79,
      confidence: 0.88,
      is_calibrated: true,
      primary_barrier: "Management of Change (MOC) Risk Assessment",
      barrier_state: "FAILED",
      credible_consequence: "Severe chemical caustic blast injury to personnel.",
      shap_values: { "Chemical Toxicity (Caustic)": 0.41, "Check Valve Reversal": 0.35, "PPE Compliance": 0.16 },
    },
    lsr_predictions: [{ lsr_id: "lsr-06", code: "LSR-06", name: "Line of Fire & Stored Energy", confidence: 0.92, rank: 1 }],
  },
  {
    id: "rep-018",
    report_uid: "HZR-2026-0075",
    report_type: "Near-Miss Precursor",
    date_time: "2026-08-28 15:10:00",
    site_name: "Hazira LNG Regasification Terminal",
    activity_name: "Cryogenic Storage Tank Inspection",
    narrative_snippet: "Full-containment LNG Tank T-101 relief valve PSV-101A failed to lift at 290 mbar due to ice accumulation in guide sleeve; popped only at 380 mbar (+31%).",
    narrative: "During statutory proof testing, PSV-101A failed to lift at set point of 290 mbar, lifting only at 380 mbar (+31% overpressure) due to ice accumulation in the guide sleeve from ambient atmospheric moisture ingress during previous cold spell. Dual standby PSV-101B verified operational.",
    equipment: "LNG Storage Tank T-101 Primary Safety Valve PSV-101A",
    location: "LNG Tank T-101 Dome Top",
    contractor_internal: "Emerson Automation Solutions",
    actual_outcome: "Identified during planned proof test; valve rebuilt with heated nitrogen purge.",
    potential_consequence: "Catastrophic overpressure rupture of 160,000 m3 cryogenic LNG storage tank.",
    psif_probability: 0.89,
    priority_score: 94,
    primary_barrier: "Pressure Safety Relief Valves (PSV) System",
    barrier_state: "FAILED",
    primary_lsr: "Bypassing Safety Controls (LSR-01)",
    review_status: "VERIFIED",
    data_origin: "FIELD_LOG",
    entities: [
      { entity_type: "EQUIPMENT", value: "Safety Valve PSV-101A", text_span: "Safety Valve PSV-101A", confidence: 0.98 },
      { entity_type: "HAZARD", value: "31% overpressure cryogenic tank", text_span: "380 mbar (+31% overpressure)", confidence: 0.95 },
    ],
    psif_prediction: {
      psif_probability: 0.89,
      priority_score: 94,
      confidence: 0.95,
      is_calibrated: true,
      primary_barrier: "Pressure Safety Relief Valves (PSV) System",
      barrier_state: "FAILED",
      credible_consequence: "Catastrophic tank roof collapse and massive vapor cloud release.",
      shap_values: { "Cryogenic Inventory Volume": 0.50, "Ice Freeze Binding": 0.31, "Dual PSV Redundancy": 0.12 },
    },
    lsr_predictions: [{ lsr_id: "lsr-01", code: "LSR-01", name: "Bypassing Safety Controls", confidence: 0.94, rank: 1 }],
  },
  {
    id: "rep-019",
    report_uid: "BMR-2026-0049",
    report_type: "Unsafe Condition",
    date_time: "2026-08-26 12:40:00",
    site_name: "Barmer Oil Gathering Station (OGS-3)",
    activity_name: "Scaffolding & Working at Heights",
    narrative_snippet: "Scaffolding board blew loose from 18m elevation on Tank TK-201 external stairway in 42 km/h wind gust; dropped into unbarricaded bund corridor.",
    narrative: "Scaffolding contractor left three scaffolding boards unclamped at 18 meters elevation on external circular stairway of tank TK-201. High wind gust (42 km/h) displaced one board, which fell to grade inside the bund wall. Area was unbarricaded at the time.",
    equipment: "Crude Storage Tank TK-201 External Stairway Scaffolding",
    location: "Tank Farm Bund 3",
    contractor_internal: "Altrad Scaffolding Services",
    actual_outcome: "Board landed on gravel without hitting personnel; scaffold tagged red.",
    potential_consequence: "Fatal blunt-force head trauma from 18-meter falling scaffold timber.",
    psif_probability: 0.80,
    priority_score: 85,
    primary_barrier: "Working at Height & Fall Prevention Controls",
    barrier_state: "FAILED",
    primary_lsr: "Working at Height (LSR-08)",
    review_status: "VERIFIED",
    data_origin: "FIELD_LOG",
    entities: [
      { entity_type: "EQUIPMENT", value: "Tank TK-201 Scaffolding", text_span: "Tank TK-201 Scaffolding", confidence: 0.95 },
      { entity_type: "HAZARD", value: "dropped scaffold board from 18m", text_span: "fell to grade from 18 meters", confidence: 0.96 },
    ],
    psif_prediction: {
      psif_probability: 0.80,
      priority_score: 85,
      confidence: 0.90,
      is_calibrated: true,
      primary_barrier: "Working at Height & Fall Prevention Controls",
      barrier_state: "FAILED",
      credible_consequence: "Fatal blunt force impact to workers below.",
      shap_values: { "Fall Elevation (18m)": 0.44, "Wind Speed Factors": 0.28, "No Exclusion Barricade": 0.22 },
    },
    lsr_predictions: [{ lsr_id: "lsr-08", code: "LSR-08", name: "Working at Height", confidence: 0.98, rank: 1 }],
  },
  {
    id: "rep-020",
    report_uid: "PDC-2026-0098",
    report_type: "Near-Miss Precursor",
    date_time: "2026-08-24 17:15:00",
    site_name: "Paradip Petrochemicals & FCC Complex",
    activity_name: "Catalyst Unloading & Transfer",
    narrative_snippet: "Triethylaluminum (TEAL) pyrophoric catalyst line flange weeped during meter calibration; nitrogen shroud blanket auto-purged enclosure preventing ignition.",
    narrative: "Triethylaluminum (TEAL) pyrophoric catalyst injection line flange developed weeping during flow meter calibration. TEAL ignites spontaneously upon contact with air. Nitrogen shroud blanket auto-purged the manifold enclosure, preventing atmospheric ignition until line was isolated.",
    equipment: "Polypropylene Polymerization Loop TEAL Injection Skid",
    location: "PP Polymerization Structure Level 3",
    contractor_internal: "AkzoNobel Specialty Chemicals",
    actual_outcome: "Nitrogen shroud successfully prevented pyrophoric air contact fire.",
    potential_consequence: "Violent pyrophoric jet flame causing rapid thermal rupture of loop reactor.",
    psif_probability: 0.93,
    priority_score: 97,
    primary_barrier: "Inert Gas Purging & Blanketing",
    barrier_state: "VERIFIED",
    primary_lsr: "Energy Isolation (LSR-03)",
    review_status: "VERIFIED",
    data_origin: "FIELD_LOG",
    entities: [
      { entity_type: "EQUIPMENT", value: "TEAL Injection Skid", text_span: "TEAL Injection Skid", confidence: 0.98 },
      { entity_type: "HAZARD", value: "pyrophoric catalyst weepage", text_span: "Triethylaluminum (TEAL)", confidence: 0.97 },
    ],
    psif_prediction: {
      psif_probability: 0.93,
      priority_score: 97,
      confidence: 0.96,
      is_calibrated: true,
      primary_barrier: "Inert Gas Purging & Blanketing",
      barrier_state: "VERIFIED",
      credible_consequence: "Catastrophic pyrophoric explosion in polymerization reactor train.",
      shap_values: { "Pyrophoric Spontaneous Ignition": 0.52, "Reactor Proximity": 0.29, "Nitrogen Inerting Integrity": 0.15 },
    },
    lsr_predictions: [{ lsr_id: "lsr-03", code: "LSR-03", name: "Energy Isolation", confidence: 0.95, rank: 1 }],
  },
  {
    id: "rep-021",
    report_uid: "MHN-2026-0118",
    report_type: "Near-Miss Precursor",
    date_time: "2026-08-22 10:05:00",
    site_name: "Mumbai High North Platform",
    activity_name: "Lifeboat Davit Inspection & Abandon Platform Drill",
    narrative_snippet: "Quarterly offshore lifeboat retrieval revealed on-load hook secondary lock half-cocked while craft was suspended 15 meters above sea level.",
    narrative: "During offshore quarterly lifeboat retrieval, on-load release hook secondary lock indicator showed half-cocked status while boat was suspended 15 meters above sea level. Winch was stopped and safety hanging pennants immediately installed prior to personnel boarding.",
    equipment: "TEMPSC Lifeboat No. 2 On-Load Release Hook",
    location: "Starboard Lifeboat Station Davit 2",
    contractor_internal: "Survitec Survival Systems",
    actual_outcome: "Safety hanging pennants installed; hook reset under supervisor oversight.",
    potential_consequence: "Catastrophic premature on-load release and fatal 15-meter free-fall into sea.",
    psif_probability: 0.88,
    priority_score: 92,
    primary_barrier: "Emergency Escape, Evacuation & Rescue Systems",
    barrier_state: "DEGRADED",
    primary_lsr: "Bypassing Safety Controls (LSR-01)",
    review_status: "VERIFIED",
    data_origin: "FIELD_LOG",
    entities: [
      { entity_type: "EQUIPMENT", value: "Lifeboat No. 2 Release Hook", text_span: "TEMPSC Lifeboat No. 2", confidence: 0.97 },
      { entity_type: "HAZARD", value: "half-cocked on-load release hook", text_span: "secondary lock indicator half-cocked", confidence: 0.95 },
    ],
    psif_prediction: {
      psif_probability: 0.88,
      priority_score: 92,
      confidence: 0.93,
      is_calibrated: true,
      primary_barrier: "Emergency Escape, Evacuation & Rescue Systems",
      barrier_state: "DEGRADED",
      credible_consequence: "Uncontrolled drop of survival craft resulting in multiple fatalities.",
      shap_values: { "Release Hook Kinematics": 0.45, "Suspended Elevation (15m)": 0.32, "Marine Sea State": 0.17 },
    },
    lsr_predictions: [{ lsr_id: "lsr-01", code: "LSR-01", name: "Bypassing Safety Controls", confidence: 0.94, rank: 1 }],
  },
  {
    id: "rep-022",
    report_uid: "DGB-2026-0041",
    report_type: "Near-Miss Precursor",
    date_time: "2026-08-20 14:30:00",
    site_name: "Digboi Refinery Complex",
    activity_name: "Pipeline Excavation & Underground Utilities",
    narrative_snippet: "Excavator bucket tooth tore warning mesh directly over live 10-inch crude oil pipeline during drainage works; pipeline was mislocated by 3 meters on drawing.",
    narrative: "Excavator bucket tooth struck warning mesh directly above 10-inch pressurized crude oil transfer pipeline during storm drain widening. Excavation permit had marked pipeline 3 meters to the east due to outdated 1988 pipeline survey drawings. Trenching stopped immediately.",
    equipment: "Hydraulic Excavator CAT 320 & Crude Pipeline TL-1",
    location: "Offsite Pipeline Corridor East Gate",
    contractor_internal: "Assam Earthmovers Ltd",
    actual_outcome: "Warning mesh stopped bucket before striking steel pipe wall.",
    potential_consequence: "Puncture of 10-inch pressurized crude trunkline, large pool fire, and refinery evacuation.",
    psif_probability: 0.85,
    priority_score: 90,
    primary_barrier: "Permit to Work (PTW) System Authorization",
    barrier_state: "FAILED",
    primary_lsr: "Work Authorization & PTW (LSR-07)",
    review_status: "PENDING",
    data_origin: "FIELD_LOG",
    entities: [
      { entity_type: "EQUIPMENT", value: "Excavator CAT 320", text_span: "Excavator CAT 320", confidence: 0.95 },
      { entity_type: "HAZARD", value: "buried live crude trunkline struck", text_span: "10-inch pressurized crude", confidence: 0.96 },
    ],
    psif_prediction: {
      psif_probability: 0.85,
      priority_score: 90,
      confidence: 0.91,
      is_calibrated: true,
      primary_barrier: "Permit to Work (PTW) System Authorization",
      barrier_state: "FAILED",
      credible_consequence: "High-pressure crude trunkline rupture and environmental contamination.",
      shap_values: { "Mechanical Strike Energy": 0.44, "As-Built Drawing Inaccuracy": 0.35, "Soil Cover Depth": 0.15 },
    },
    lsr_predictions: [{ lsr_id: "lsr-07", code: "LSR-07", name: "Work Authorization & PTW", confidence: 0.96, rank: 1 }],
  },
  {
    id: "rep-023",
    report_uid: "HZR-2026-0081",
    report_type: "Equipment Failure",
    date_time: "2026-08-18 09:10:00",
    site_name: "Hazira LNG Regasification Terminal",
    activity_name: "Submerged Combustion Vaporizer Maintenance",
    narrative_snippet: "Fuel gas pilot solenoid valve SV-204 stayed energized for 12 seconds without flame detection during SCV start-up (emergency cutoff is 3 seconds).",
    narrative: "Flame scanner failed to detect fuel gas pilot flame during start-up sequence, but fuel gas solenoid valve SV-204 remained energized for 12 seconds instead of emergency 3-second safety cutoff time. Combustion chamber vented to atmosphere prior to reignition attempt.",
    equipment: "Submerged Combustion Vaporizer SCV-B102 Burner Skid",
    location: "Vaporization Unit Area 4",
    contractor_internal: "John Zink Hamworthy Combustion",
    actual_outcome: "Console operator manually hit emergency fuel trip; chamber purged.",
    potential_consequence: "Delayed ignition fuel gas explosion blowing apart vaporizer firetubes.",
    psif_probability: 0.77,
    priority_score: 82,
    primary_barrier: "Burner Management & Flame Safeguard Controls",
    barrier_state: "DEGRADED",
    primary_lsr: "Bypassing Safety Controls (LSR-01)",
    review_status: "VERIFIED",
    data_origin: "SCADA_ALARM",
    entities: [
      { entity_type: "EQUIPMENT", value: "SCV Burner B102", text_span: "SCV Burner B102", confidence: 0.97 },
      { entity_type: "HAZARD", value: "12 second unignited fuel gas injection", text_span: "remained energized for 12 seconds", confidence: 0.94 },
    ],
    psif_prediction: {
      psif_probability: 0.77,
      priority_score: 82,
      confidence: 0.88,
      is_calibrated: true,
      primary_barrier: "Burner Management & Flame Safeguard Controls",
      barrier_state: "DEGRADED",
      credible_consequence: "Firebox deflagration and high-energy structural fragmentation.",
      shap_values: { "Fuel Gas Accumulation": 0.42, "Burner Safeguard Delay": 0.33, "Purge Cycle Timing": 0.19 },
    },
    lsr_predictions: [{ lsr_id: "lsr-01", code: "LSR-01", name: "Bypassing Safety Controls", confidence: 0.92, rank: 1 }],
  },
  {
    id: "rep-024",
    report_uid: "BMR-2026-0056",
    report_type: "Equipment Failure",
    date_time: "2026-08-16 16:50:00",
    site_name: "Barmer Oil Gathering Station (OGS-3)",
    activity_name: "High-Pressure Gas Injection & Compression",
    narrative_snippet: "Crosshead pin temperature spiked to 112°C on booster compressor K-101; operator discovered lube oil needle valve throttled with unauthorized wire wrap.",
    narrative: "Crosshead pin temperature sensor on 2nd stage cylinder exceeded trip limit (95°C) reaching 112°C. Operator found lube oil supply needle valve partially throttled by unauthorized wire wrap. Vibration was 18 mm/s RMS.",
    equipment: "Gas Booster Reciprocating Compressor K-101 Crosshead",
    location: "Compression House Bay 2",
    contractor_internal: "Ariel Compressor Technical Support",
    actual_outcome: "Compressor auto-tripped on high temperature; crankcase inspected.",
    potential_consequence: "Mechanical seizure, connecting rod puncturing crankcase, and explosive lube oil mist blast.",
    psif_probability: 0.84,
    priority_score: 89,
    primary_barrier: "Machinery Vibration & Thermal Protection Trips",
    barrier_state: "DEGRADED",
    primary_lsr: "Bypassing Safety Controls (LSR-01)",
    review_status: "VERIFIED",
    data_origin: "SCADA_ALARM",
    entities: [
      { entity_type: "EQUIPMENT", value: "Compressor K-101", text_span: "Compressor K-101", confidence: 0.98 },
      { entity_type: "HAZARD", value: "crosshead thermal runaway 112°C", text_span: "112°C", confidence: 0.93 },
    ],
    psif_prediction: {
      psif_probability: 0.84,
      priority_score: 89,
      confidence: 0.91,
      is_calibrated: true,
      primary_barrier: "Machinery Vibration & Thermal Protection Trips",
      barrier_state: "DEGRADED",
      credible_consequence: "Catastrophic mechanical disintegration and crankcase explosion.",
      shap_values: { "Lube Oil Starvation": 0.45, "Unauthorized Wire Tampering": 0.32, "Vibration Elevation": 0.17 },
    },
    lsr_predictions: [{ lsr_id: "lsr-01", code: "LSR-01", name: "Bypassing Safety Controls", confidence: 0.95, rank: 1 }],
  },
  {
    id: "rep-025",
    report_uid: "PDC-2026-0105",
    report_type: "Near-Miss Precursor",
    date_time: "2026-08-14 11:35:00",
    site_name: "Paradip Petrochemicals & FCC Complex",
    activity_name: "Sulfur Recovery Unit Maintenance",
    narrative_snippet: "Tail gas diverter damper stuck 30% open routing 12% H2S acid gas stream toward cold incinerator bypass; perimeter gas grid alarmed at Level 2.",
    narrative: "Tail gas diverter damper stuck at 30% open position during transition, routing acid gas containing 12% H2S toward the shutdown incinerator bypass stack. Area H2S perimeter sensors triggered Level 2 site siren. Wind was blowing toward main gate.",
    equipment: "SRU Claus Tail Gas Diverter Damper D-501",
    location: "Sulfur Recovery Plant Battery Limit",
    contractor_internal: "Jacobs Engineering Group",
    actual_outcome: "Console operator switched to high-pressure emergency flare in 45 seconds.",
    potential_consequence: "Lethal toxic H2S plume dispersion toward occupied control building and gate.",
    psif_probability: 0.95,
    priority_score: 99,
    primary_barrier: "Fixed Gas & Flame Detection Grid",
    barrier_state: "VERIFIED",
    primary_lsr: "Line of Fire & Stored Energy (LSR-06)",
    review_status: "VERIFIED",
    data_origin: "SCADA_ALARM",
    entities: [
      { entity_type: "EQUIPMENT", value: "Claus Tail Gas Damper D-501", text_span: "Diverter Damper D-501", confidence: 0.97 },
      { entity_type: "HAZARD", value: "12% toxic H2S acid gas stream", text_span: "12% H2S acid gas", confidence: 0.99 },
    ],
    psif_prediction: {
      psif_probability: 0.95,
      priority_score: 99,
      confidence: 0.97,
      is_calibrated: true,
      primary_barrier: "Fixed Gas & Flame Detection Grid",
      barrier_state: "VERIFIED",
      credible_consequence: "Multiple acute fatalities from atmospheric toxic H2S release.",
      shap_values: { "H2S Concentration (120,000 ppm)": 0.54, "Off-Site Wind Direction": 0.28, "Damper Mechanical Jam": 0.16 },
    },
    lsr_predictions: [{ lsr_id: "lsr-06", code: "LSR-06", name: "Line of Fire & Stored Energy", confidence: 0.98, rank: 1 }],
  },
  {
    id: "rep-026",
    report_uid: "MHN-2026-0125",
    report_type: "Hazard Observation",
    date_time: "2026-08-12 15:20:00",
    site_name: "Mumbai High North Platform",
    activity_name: "Produced Water Treatment & Sand Jetting",
    narrative_snippet: "High-pressure desander sand jet flushing line (60 bar) developed pinhole jet leak at 90° elbow due to accelerated particulate erosive wear.",
    narrative: "High-pressure sand flushing line operating at 60 bar experienced rapid erosive wall thinning, developing an ultrasonic pinhole leak at the 90-degree long radius elbow. Sand acoustic monitor had been offline for maintenance.",
    equipment: "Hydrocyclone Desander Vessel V-203 Sand Jetting Loop",
    location: "Produced Water Module Lower Mezzanine",
    contractor_internal: "Internal Maintenance Crew",
    actual_outcome: "Isolation valve closed by field operator; no injuries.",
    potential_consequence: "Full circumferential elbow blowout and pressurized sand-slurry jet cutting neighboring instrumentation.",
    psif_probability: 0.71,
    priority_score: 76,
    primary_barrier: "Erosion & Corrosion Monitoring Barriers",
    barrier_state: "FAILED",
    primary_lsr: "Line of Fire & Stored Energy (LSR-06)",
    review_status: "PENDING",
    data_origin: "FIELD_LOG",
    entities: [
      { entity_type: "EQUIPMENT", value: "Desander Vessel V-203", text_span: "Desander Vessel V-203", confidence: 0.96 },
      { entity_type: "HAZARD", value: "60 bar sand slurry jet", text_span: "60 bar", confidence: 0.92 },
    ],
    psif_prediction: {
      psif_probability: 0.71,
      priority_score: 76,
      confidence: 0.86,
      is_calibrated: true,
      primary_barrier: "Erosion & Corrosion Monitoring Barriers",
      barrier_state: "FAILED",
      credible_consequence: "High-pressure erosive erosion blowout in offshore module.",
      shap_values: { "Particulate Velocity Erosion": 0.40, "Monitor Offline": 0.34, "Offshore Congestion": 0.18 },
    },
    lsr_predictions: [{ lsr_id: "lsr-06", code: "LSR-06", name: "Line of Fire & Stored Energy", confidence: 0.89, rank: 1 }],
  },
  {
    id: "rep-027",
    report_uid: "DGB-2026-0048",
    report_type: "Equipment Failure",
    date_time: "2026-08-10 13:45:00",
    site_name: "Digboi Refinery Complex",
    activity_name: "Bitumen Blowing & Drum Filling",
    narrative_snippet: "Scrubber circulation pump tripped on electrical overload; reactor core temperature surged from 240°C to 285°C in 8 mins towards auto-ignition point.",
    narrative: "Scrubber water circulating pump tripped on electrical overload. Reactor temperature spiked from 240°C to 285°C within 8 minutes, nearing auto-ignition temperature of heavy hydrocarbons. Emergency steam quenching was manually injected.",
    equipment: "Bitumen Blowing Column R-601 Water Scrubber System",
    location: "Bitumen Manufacturing Unit Block 3",
    contractor_internal: "Internal Maintenance Crew",
    actual_outcome: "Emergency steam quench contained temperature rise; cooled to 220°C.",
    potential_consequence: "Thermal runaway deflagration and rupture of bitumen reactor column.",
    psif_probability: 0.81,
    priority_score: 87,
    primary_barrier: "Emergency Steam & Deluge Quenching System",
    barrier_state: "VERIFIED",
    primary_lsr: "Work Authorization & PTW (LSR-07)",
    review_status: "VERIFIED",
    data_origin: "FIELD_LOG",
    entities: [
      { entity_type: "EQUIPMENT", value: "Bitumen Column R-601", text_span: "Bitumen Column R-601", confidence: 0.97 },
      { entity_type: "HAZARD", value: "thermal runaway 285°C", text_span: "spiked from 240°C to 285°C", confidence: 0.94 },
    ],
    psif_prediction: {
      psif_probability: 0.81,
      priority_score: 87,
      confidence: 0.90,
      is_calibrated: true,
      primary_barrier: "Emergency Steam & Deluge Quenching System",
      barrier_state: "VERIFIED",
      credible_consequence: "Column rupture and atmospheric bitumen fireball.",
      shap_values: { "Exothermic Reaction Kinetics": 0.44, "Pump Trip Common Cause": 0.31, "Steam Quench Action": 0.17 },
    },
    lsr_predictions: [{ lsr_id: "lsr-07", code: "LSR-07", name: "Work Authorization & PTW", confidence: 0.92, rank: 1 }],
  },
  {
    id: "rep-028",
    report_uid: "HZR-2026-0088",
    report_type: "Unsafe Condition",
    date_time: "2026-08-08 11:00:00",
    site_name: "Hazira LNG Regasification Terminal",
    activity_name: "Electrical Substation Maintenance",
    narrative_snippet: "Contractor lanyard tied off to deluge pull-cable; 20kg tension tripped 2500 L/min seawater flood directly into 33 kV transformer bay.",
    narrative: "Contractor painter tied off scaffolding safety lanyard directly to the manual release pull-cable of the transformer deluge water spray system. Cable was pulled with 20 kg tension, causing deluge valve to trip open, flooding the 33 kV transformer bay with 2500 L/min sea water.",
    equipment: "33 kV Transformer TX-02 Deluge Fire Protection Skid",
    location: "Main Substation Outdoor Yard Bay 2",
    contractor_internal: "Shapoorji Pallonji Industrial",
    actual_outcome: "Substation operator tripped transformer breaker before saltwater flashover occurred.",
    potential_consequence: "33 kV explosive arc flash flashover and total blackout of cryogenic sendout pumps.",
    psif_probability: 0.76,
    priority_score: 80,
    primary_barrier: "Deluge & Fire Water Suppression Systems",
    barrier_state: "DEGRADED",
    primary_lsr: "Bypassing Safety Controls (LSR-01)",
    review_status: "VERIFIED",
    data_origin: "FIELD_LOG",
    entities: [
      { entity_type: "EQUIPMENT", value: "Transformer TX-02", text_span: "Transformer TX-02", confidence: 0.98 },
      { entity_type: "HAZARD", value: "saltwater deluge onto live 33 kV bus", text_span: "33 kV transformer bay", confidence: 0.96 },
    ],
    psif_prediction: {
      psif_probability: 0.76,
      priority_score: 80,
      confidence: 0.87,
      is_calibrated: true,
      primary_barrier: "Deluge & Fire Water Suppression Systems",
      barrier_state: "DEGRADED",
      credible_consequence: "Massive 33 kV phase-to-ground fault and explosive oil tank rupture.",
      shap_values: { "High Voltage Potential (33 kV)": 0.43, "Conductive Sea Water": 0.36, "Improper Tie-off": 0.17 },
    },
    lsr_predictions: [{ lsr_id: "lsr-01", code: "LSR-01", name: "Bypassing Safety Controls", confidence: 0.91, rank: 1 }],
  },
  {
    id: "rep-029",
    report_uid: "BMR-2026-0062",
    report_type: "Near-Miss Precursor",
    date_time: "2026-08-06 14:15:00",
    site_name: "Barmer Oil Gathering Station (OGS-3)",
    activity_name: "Heavy Transport & Logistics",
    narrative_snippet: "30,000L crude oil tanker truck reversed into gantry rack without banksman, bending shear pin on loading arm breakaway coupling by 6mm.",
    narrative: "Tanker truck carrying 30,000 liters of crude oil reversed into the loading arm rack without a designated banksman. Rear bumper impacted the loading arm breakaway coupling, bending the shear pin by 6mm. No liquid spill occurred.",
    equipment: "Road Tanker Loading Gantry Bay 3 Breakaway Coupling",
    location: "Crude Dispatch Terminal Loading Rack",
    contractor_internal: "Indian Oil Transport Logistics",
    actual_outcome: "Loading arm automatically locked, shear coupling inspected and replaced.",
    potential_consequence: "Complete shear coupling rupture during active 2000 L/min loading resulting in pool fire.",
    psif_probability: 0.70,
    priority_score: 74,
    primary_barrier: "Loading Arm Dry Breakaway Safety Couplings",
    barrier_state: "VERIFIED",
    primary_lsr: "Safe Driving & Vehicle Movement (LSR-09)",
    review_status: "VERIFIED",
    data_origin: "FIELD_LOG",
    entities: [
      { entity_type: "EQUIPMENT", value: "Loading Gantry Bay 3", text_span: "Loading Gantry Bay 3", confidence: 0.96 },
      { entity_type: "HAZARD", value: "30,000L crude tanker impact", text_span: "30,000 liters of crude oil", confidence: 0.95 },
    ],
    psif_prediction: {
      psif_probability: 0.70,
      priority_score: 74,
      confidence: 0.85,
      is_calibrated: true,
      primary_barrier: "Loading Arm Dry Breakaway Safety Couplings",
      barrier_state: "VERIFIED",
      credible_consequence: "Massive crude oil release at truck gantry and vapor cloud flash fire.",
      shap_values: { "Vehicle Kinetic Momentum": 0.42, "Missing Banksman": 0.35, "Breakaway Integrity": 0.17 },
    },
    lsr_predictions: [{ lsr_id: "lsr-09", code: "LSR-09", name: "Safe Driving & Vehicle Movement", confidence: 0.97, rank: 1 }],
  },
  {
    id: "rep-030",
    report_uid: "PDC-2026-0112",
    report_type: "Near-Miss Precursor",
    date_time: "2026-08-04 16:30:00",
    site_name: "Paradip Petrochemicals & FCC Complex",
    activity_name: "Flare System Maintenance & Tip Ignition",
    narrative_snippet: "Radar high-level switch on flare knockout drum failed in heavy rain; visual sight glass showed liquid hydrocarbon condensate at 85% capacity.",
    narrative: "During heavy monsoon downpour, high-level radar switch on flare KO drum failed to trigger alarm due to condensation on horn antenna. Visual inspection through sight glass showed liquid hydrocarbon condensate at 85% drum capacity, threatening liquid carryover to elevated flare.",
    equipment: "Ground Flare Knockout Drum V-901 Level Instrumentation",
    location: "Main Flare System Area Block 8",
    contractor_internal: "Yokogawa India Instrumentation",
    actual_outcome: "Manual start of emergency slop pump evacuated liquid in time.",
    potential_consequence: "Burning liquid hydrocarbon rainout from 100m flare tip showering down upon FCC unit.",
    psif_probability: 0.89,
    priority_score: 93,
    primary_barrier: "Closed Loop Flare Knockout System",
    barrier_state: "FAILED",
    primary_lsr: "Bypassing Safety Controls (LSR-01)",
    review_status: "VERIFIED",
    data_origin: "FIELD_LOG",
    entities: [
      { entity_type: "EQUIPMENT", value: "Flare KO Drum V-901", text_span: "Flare KO Drum V-901", confidence: 0.98 },
      { entity_type: "HAZARD", value: "85% liquid condensate carryover risk", text_span: "85% drum capacity", confidence: 0.96 },
    ],
    psif_prediction: {
      psif_probability: 0.89,
      priority_score: 93,
      confidence: 0.94,
      is_calibrated: true,
      primary_barrier: "Closed Loop Flare Knockout System",
      barrier_state: "FAILED",
      credible_consequence: "Flaming hydrocarbon rainout and ground pool fires across refinery.",
      shap_values: { "Flare Carryover Hazard": 0.48, "Radar Antenna Moisture": 0.31, "Sight Glass Redundancy": 0.14 },
    },
    lsr_predictions: [{ lsr_id: "lsr-01", code: "LSR-01", name: "Bypassing Safety Controls", confidence: 0.94, rank: 1 }],
  },
  {
    id: "rep-031",
    report_uid: "MHN-2026-0133",
    report_type: "Near-Miss Precursor",
    date_time: "2026-08-02 09:15:00",
    site_name: "Mumbai High North Platform",
    activity_name: "Corrosion Coupon Retrieval under Pressure",
    narrative_snippet: "High-pressure retriever tool barrel backed off 2 threads under 140 bar flowline kick before safety collar caught thread during coupon retrieval.",
    narrative: "Technician crack-opened the Cosasco high-pressure retriever valve at 140 bar flowline pressure without confirming the retriever pressure equalizing valve was fully seated. Retriever tool barrel backed off two threads under hydraulic kick before safety collar caught the thread.",
    equipment: "Subsea Flowline Riser R-04 Cosasco Retriever Fitting",
    location: "Cellar Deck East Flowline Manifold",
    contractor_internal: "Rohrback Cosasco Systems",
    actual_outcome: "Safety collar mechanically prevented tool ejection; line isolated.",
    potential_consequence: "Retriever tool projectile ejection under 140 bar killing operator and initiating full riser blowout.",
    psif_probability: 0.91,
    priority_score: 96,
    primary_barrier: "Positive Physical Isolation (Double Block & Bleed)",
    barrier_state: "FAILED",
    primary_lsr: "Line of Fire & Stored Energy (LSR-06)",
    review_status: "UNDER_INVESTIGATION",
    data_origin: "FIELD_LOG",
    entities: [
      { entity_type: "EQUIPMENT", value: "Riser R-04 Cosasco Fitting", text_span: "Riser R-04 Access Fitting", confidence: 0.97 },
      { entity_type: "HAZARD", value: "140 bar hydraulic projectile energy", text_span: "140 bar flowline pressure", confidence: 0.98 },
    ],
    psif_prediction: {
      psif_probability: 0.91,
      priority_score: 96,
      confidence: 0.95,
      is_calibrated: true,
      primary_barrier: "Positive Physical Isolation (Double Block & Bleed)",
      barrier_state: "FAILED",
      credible_consequence: "Fatal projectile strike and uncontained subsea flowline blowout.",
      shap_values: { "High Operating Pressure (140 bar)": 0.49, "Equalizing Valve Misalignment": 0.32, "Mechanical Stop Ring": 0.14 },
    },
    lsr_predictions: [{ lsr_id: "lsr-06", code: "LSR-06", name: "Line of Fire & Stored Energy", confidence: 0.97, rank: 1 }],
  },
  {
    id: "rep-032",
    report_uid: "DGB-2026-0055",
    report_type: "Near-Miss Precursor",
    date_time: "2026-07-28 14:50:00",
    site_name: "Digboi Refinery Complex",
    activity_name: "Solvent Dewaxing & Ammonia Refrigeration",
    narrative_snippet: "Anhydrous ammonia gas detected at 45 ppm around refrigeration compressor shaft packing; emergency water absorption curtain auto-activated.",
    narrative: "Anhydrous ammonia vapor leak detected at 45 ppm around compressor shaft packing. Emergency water curtain absorption system auto-activated. Two operators in full hazmat Level B suits safely isolated suction and discharge manual block valves.",
    equipment: "Ammonia Refrigeration Compressor CH-201 Shaft Packing",
    location: "Lube Oil Dewaxing Unit Ammonia Shed",
    contractor_internal: "Internal Maintenance Crew",
    actual_outcome: "Water curtain scrubbed 92% of vapor; zero casualties.",
    potential_consequence: "Massive toxic anhydrous ammonia vapor cloud engulfing refinery boundary and local town.",
    psif_probability: 0.87,
    priority_score: 92,
    primary_barrier: "Fixed Gas & Flame Detection Grid",
    barrier_state: "VERIFIED",
    primary_lsr: "Energy Isolation (LSR-03)",
    review_status: "VERIFIED",
    data_origin: "FIELD_LOG",
    entities: [
      { entity_type: "EQUIPMENT", value: "Ammonia Chiller CH-201", text_span: "Ammonia Chiller Unit CH-201", confidence: 0.98 },
      { entity_type: "HAZARD", value: "45 ppm toxic anhydrous ammonia", text_span: "45 ppm", confidence: 0.96 },
    ],
    psif_prediction: {
      psif_probability: 0.87,
      priority_score: 92,
      confidence: 0.93,
      is_calibrated: true,
      primary_barrier: "Fixed Gas & Flame Detection Grid",
      barrier_state: "VERIFIED",
      credible_consequence: "Toxic airborne dispersion with severe civilian respiratory casualties.",
      shap_values: { "Chemical Toxicity (Ammonia)": 0.47, "Shaft Packing Extrusion": 0.32, "Water Absorption Curtain": 0.15 },
    },
    lsr_predictions: [{ lsr_id: "lsr-03", code: "LSR-03", name: "Energy Isolation", confidence: 0.94, rank: 1 }],
  },
  {
    id: "rep-033",
    report_uid: "HZR-2026-0096",
    report_type: "Near-Miss Precursor",
    date_time: "2026-07-25 11:40:00",
    site_name: "Hazira LNG Regasification Terminal",
    activity_name: "Cryogenic High-Pressure Sendout Pumps",
    narrative_snippet: "Sendout Pump P-104B tripped on bearing vibration; cryogenic discharge check valve bound partially open, allowing 95 bar sendout gas to backflow into 4 bar suction drum.",
    narrative: "Pump P-104B tripped on motor bearing high vibration (7.8 mm/s). The dual-plate discharge check valve failed to close completely due to cryogenic thermal contraction binding, allowing 95 bar high-pressure sendout header gas to backflow into low-pressure suction drum at 4 bar.",
    equipment: "Submerged LNG Sendout Pump P-104B Discharge Check Valve",
    location: "High-Pressure LNG Sendout Pump Bay 4",
    contractor_internal: "Cryostar Submerged Motor Pumps",
    actual_outcome: "Suction drum PSV popped to flare; emergency motor-operated suction valve closed.",
    potential_consequence: "Catastrophic overpressure rupture of cryogenic suction drum and massive BLEVE release.",
    psif_probability: 0.94,
    priority_score: 98,
    primary_barrier: "Emergency Shutdown Valve (SDV/ESD Automation)",
    barrier_state: "FAILED",
    primary_lsr: "Bypassing Safety Controls (LSR-01)",
    review_status: "VERIFIED",
    data_origin: "FIELD_LOG",
    entities: [
      { entity_type: "EQUIPMENT", value: "Sendout Pump P-104B", text_span: "Sendout Pump P-104B", confidence: 0.98 },
      { entity_type: "HAZARD", value: "95 bar reverse gas backflow into 4 bar vessel", text_span: "95 bar high-pressure sendout header", confidence: 0.97 },
    ],
    psif_prediction: {
      psif_probability: 0.94,
      priority_score: 98,
      confidence: 0.96,
      is_calibrated: true,
      primary_barrier: "Emergency Shutdown Valve (SDV/ESD Automation)",
      barrier_state: "FAILED",
      credible_consequence: "Violent pressure rupture of low-pressure cryogenic vessel and terminal explosion.",
      shap_values: { "Extreme Differential Pressure (91 bar)": 0.52, "Cryogenic Thermal Binding": 0.31, "Relief Header Sizing": 0.13 },
    },
    lsr_predictions: [{ lsr_id: "lsr-01", code: "LSR-01", name: "Bypassing Safety Controls", confidence: 0.98, rank: 1 }],
  },
];

export const FALLBACK_PRECURSORS: PrecursorCluster[] = [
  {
    id: "prec-001",
    name: "High-Pressure Gas Lift Flange & Packing Weeps",
    summary: "Repeated small-scale gas and condensate weepage from 90-110 bar injection manifolds during offshore vibration cycles.",
    coherence_score: 0.91,
    occurrence_count: 8,
    primary_hazard: "Loss of Containment (Pressurized Methane)",
    primary_barrier: "Positive Physical Isolation (Double Block & Bleed)",
    primary_lsr: "Energy Isolation (LSR-03)",
    trend_status: "INCREASING",
    first_seen: "2026-08-10",
    latest_seen: "2026-09-14",
    affected_sites: ["Mumbai High North Platform", "Barmer Oil Gathering Station (OGS-3)"],
    affected_activities: ["Valve Isolation & Maintenance", "High-Pressure Pipeline Pigging"],
    example_report_ids: ["rep-001", "rep-008", "rep-016", "rep-031"],
  },
  {
    id: "prec-002",
    name: "Permit to Work & Hot Work Ignition Boundary Gaps",
    summary: "Residual light hydrocarbon vapors detected in drainage sumps and trenches within 5 meters of active torch cutting.",
    coherence_score: 0.88,
    occurrence_count: 6,
    primary_hazard: "Vapor Cloud Flash Fire",
    primary_barrier: "LEL Flammable & H2S Optical Gas Detectors",
    primary_lsr: "Hot Work Control (LSR-04)",
    trend_status: "STABLE",
    first_seen: "2026-08-15",
    latest_seen: "2026-09-13",
    affected_sites: ["Digboi Refinery Complex", "Paradip Petrochemicals & FCC Complex"],
    affected_activities: ["Hot Work & High-Energy Welding"],
    example_report_ids: ["rep-002", "rep-010", "rep-015", "rep-022"],
  },
  {
    id: "prec-003",
    name: "Rotating Equipment ESD Bypass During Calibration",
    summary: "Temporary instrumentation override jumpers left active on critical compressor trips without formal MOC sign-off.",
    coherence_score: 0.94,
    occurrence_count: 4,
    primary_hazard: "Uncontrolled Overpressure / Catastrophic Seal Failure",
    primary_barrier: "Emergency Shutdown Valve (SDV/ESD Automation)",
    primary_lsr: "Bypassing Safety Controls (LSR-01)",
    trend_status: "ELEVATED",
    first_seen: "2026-09-01",
    latest_seen: "2026-09-14",
    affected_sites: ["Hazira LNG Regasification Terminal"],
    affected_activities: ["High-Pressure Pipeline Pigging"],
    example_report_ids: ["rep-003", "rep-009", "rep-013", "rep-018", "rep-023", "rep-033"],
  },
  {
    id: "prec-004",
    name: "Inert Gas Life-Support Coupling Anomalies",
    summary: "Breathing air pressure dips and hose fittings degrading during nitrogen-blanketed catalyst bed entries.",
    coherence_score: 0.87,
    occurrence_count: 5,
    primary_hazard: "Nitrogen Asphyxiation (IDLH)",
    primary_barrier: "Pre-Entry Gas Free Certification & Continuous Sniffing",
    primary_lsr: "Confined Space Entry (LSR-02)",
    trend_status: "HIGH_RISK",
    first_seen: "2026-08-20",
    latest_seen: "2026-09-15",
    affected_sites: ["Paradip Petrochemicals & FCC Complex", "Digboi Refinery Complex"],
    affected_activities: ["Confined Space & Vessel Entry"],
    example_report_ids: ["rep-005", "rep-014", "rep-020", "rep-025", "rep-032"],
  },
];

export const FALLBACK_AUDIT_LOG: AuditEntry[] = [
  {
    id: "aud-001",
    timestamp: "2026-09-15T13:45:10Z",
    user_id: "usr-001",
    user_name: "Priya Sharma",
    user_email: "analyst@suraksha.ai",
    user_role: "HSE_ANALYST",
    action: "VERIFY_PSIF_SCORE",
    entity_type: "REPORT",
    entity_id: "MHN-2026-0089",
    details: { pSIF_score: 0.84, action_taken: "Escalated to Offshore Asset Manager" },
    ip_address: "10.14.82.11",
  },
  {
    id: "aud-002",
    timestamp: "2026-09-15T12:20:00Z",
    user_id: "usr-002",
    user_name: "Rajesh Verma",
    user_email: "manager@suraksha.ai",
    user_role: "HSE_MANAGER",
    action: "CONFIRM_BARRIER_OVERRIDE",
    entity_type: "BARRIER",
    entity_id: "BAR-ENG-02",
    details: { site: "Hazira LNG Terminal", reason: "MOC-2026-091 approved for dry gas seal replacement" },
    ip_address: "10.14.82.25",
  },
  {
    id: "aud-003",
    timestamp: "2026-09-15T11:05:44Z",
    user_id: "usr-003",
    user_name: "Dr. Aris Thorne",
    user_email: "scientist@suraksha.ai",
    user_role: "DATA_SCIENTIST",
    action: "VALIDATE_MODEL_CALIBRATION",
    entity_type: "MODEL",
    entity_id: "psif-xgboost-v2.4",
    details: { pr_auc: 0.88, calibration_method: "Platt Sigmoid", status: "HEALTHY" },
    ip_address: "10.14.90.104",
  },
  {
    id: "aud-004",
    timestamp: "2026-09-15T09:30:12Z",
    user_id: "usr-004",
    user_name: "Vikramaditya Sen",
    user_email: "admin@suraksha.ai",
    user_role: "ADMINISTRATOR",
    action: "SYSTEM_DIAGNOSTICS_INSPECTION",
    entity_type: "INFRASTRUCTURE",
    entity_id: "openai-safety-cluster",
    details: { node_health: "OPTIMAL", model: "gpt-4o" },
    ip_address: "10.14.80.1",
  },
];

export const FALLBACK_ALERTS: AlertItem[] = [
  {
    id: "alt-001",
    alert_type: "CRITICAL_BARRIER_FAIL",
    severity: "CRITICAL",
    title: "Double Block & Bleed Failure on 110 Bar Gas Lift",
    message: "Report MHN-2026-0089 confirmed active passing on block valve bonnet seal at Mumbai High North.",
    report_id: "rep-001",
    is_acknowledged: false,
    created_at: "2026-09-15T12:00:00Z",
  },
  {
    id: "alt-002",
    alert_type: "UNAUTHORIZED_BYPASS",
    severity: "CRITICAL",
    title: "Unapproved ESD Override on BOG Compressor",
    message: "Hazira Terminal report HZR-2026-0052 indicates interlock trip bypass without verified MOC documentation.",
    report_id: "rep-003",
    is_acknowledged: false,
    created_at: "2026-09-15T11:45:00Z",
  },
  {
    id: "alt-003",
    alert_type: "IDLH_ATMOSPHERE_LEAK",
    severity: "HIGH",
    title: "Breathing Air Manifold Pressure Dip in Nitrogen Vessel",
    message: "Paradip complex vessel entry R-301 attendant flagged secondary air regulator pressure drop.",
    report_id: "rep-005",
    is_acknowledged: false,
    created_at: "2026-09-15T08:30:00Z",
  },
];

export const FALLBACK_DASHBOARD_SUMMARY: DashboardSummary = {
  total_reports: 33,
  psif_priority_count: 8,
  pending_reviews: 5,
  active_barriers: 18,
  unacknowledged_alerts: 3,
  barrier_states: {
    VERIFIED: 22,
    UNVERIFIED: 8,
    FAILED: 3,
  },
  monthly_trend: [
    { month: "Apr 2026", total_reports: 16, psif_priority: 3, psif_density: 0.19 },
    { month: "May 2026", total_reports: 22, psif_priority: 4, psif_density: 0.18 },
    { month: "Jun 2026", total_reports: 27, psif_priority: 6, psif_density: 0.22 },
    { month: "Jul 2026", total_reports: 34, psif_priority: 7, psif_density: 0.21 },
    { month: "Aug 2026", total_reports: 38, psif_priority: 8, psif_density: 0.21 },
    { month: "Sep 2026", total_reports: 42, psif_priority: 10, psif_density: 0.24 },
  ],
  barrier_health: [
    { name: "Double Block & Bleed Isolation", code: "BAR-ENG-01", verified: 28, unverified: 3, failed: 2 },
    { name: "Emergency Shutdown Valves", code: "BAR-ENG-02", verified: 31, unverified: 1, failed: 1 },
    { name: "LEL Optical Gas Detectors", code: "BAR-ENG-03", verified: 29, unverified: 4, failed: 0 },
    { name: "Permit to Work Verification", code: "BAR-PROC-01", verified: 30, unverified: 2, failed: 1 },
    { name: "Confined Space Gas Free Testing", code: "BAR-PROC-03", verified: 26, unverified: 5, failed: 2 },
  ],
  top_alerts: FALLBACK_ALERTS,
  recent_activity: FALLBACK_AUDIT_LOG,
  ollama_status: "connected",
  ollama_mode: "OPENAI_INTELLIGENCE",
  available_models: ["gpt-4o", "gpt-4o-mini"],
};

export const FALLBACK_MODEL_HEALTH: ModelHealth = {
  nlp: {
    model: "Transformer NER (Indian O&G Specialized)",
    version: "2.4.1",
    average_latency_ms: 18.4,
    status: "HEALTHY",
    extraction_confidence_avg: 0.94,
  },
  psif: {
    model: "Calibrated Gradient Boosted Ensemble",
    version: "3.1.0",
    calibration_method: "Platt Sigmoid Scaling",
    is_calibrated: true,
    calibration_percentage: 100,
    pr_auc: 0.88,
    f2_score: 0.86,
    total_evaluated_records: 1240,
    status: "HEALTHY",
  },
  lsr: {
    model: "IOGP Multi-Label Transformer Classifier",
    supported_rules: 9,
    macro_f1: 0.91,
    micro_f1: 0.93,
    status: "HEALTHY",
  },
  clustering: {
    method: "HDBSCAN + SBERT Embeddings",
    cluster_count: 4,
    coherence_score_avg: 0.90,
    status: "HEALTHY",
  },
  llm: {
    status: "connected",
    provider: "OpenAI (GPT-4o)",
    configured_model: "gpt-4o",
    active_memory_mb: 0,
    quantization: "Frontier Float16",
    air_gapped: false,
  },
  data_drift: {
    "Equipment Vocabulary Drift": "0.02 (Minimal)",
    "Hazard Distribution Shift": "0.04 (Stable)",
    "pSIF Baseline Consistency": "99.1%",
  },
};

export const FALLBACK_KNOWLEDGE_DOCS = [
  {
    id: "doc-001",
    title: "IOGP Report 459: Life-Saving Rules Guidance & Implementation",
    filename: "IOGP_Report_459_LifeSavingRules_2023.pdf",
    category: "Global Regulatory Standard",
    document_type: "REGULATORY",
    source_org: "IOGP",
    source_authority: "International Association of Oil & Gas Producers",
    version: "2023.2",
    chunk_count: 142,
    embedding_model: "text-embedding-3-small",
    uploaded_at: "2026-08-15T09:30:00Z",
    status: "INDEXED",
    vector_count: 142,
    summary: "Mandatory standard for high-hazard work controls: Bypassing safety controls, Confined space, Energy isolation, Hot work, Line of fire, and PTW systems.",
  },
  {
    id: "doc-002",
    title: "OSHA 29 CFR 1910.146: Permit-Required Confined Spaces",
    filename: "OSHA_1910_146_Confined_Spaces_Standard.pdf",
    category: "Process Safety Standard",
    document_type: "MANDATORY",
    source_org: "OSHA",
    source_authority: "Occupational Safety & Health Administration (US DOL)",
    version: "1910.146",
    chunk_count: 98,
    embedding_model: "text-embedding-3-small",
    uploaded_at: "2026-08-18T14:15:00Z",
    status: "INDEXED",
    vector_count: 98,
    summary: "Regulatory mandates for atmospheric testing, continuous sniffing, ventilation, isolation, and staged emergency rescue equipment.",
  },
  {
    id: "doc-003",
    title: "OISD-STD-105: Work Permit System for Oil & Gas Installations",
    filename: "OISD_STD_105_Permit_To_Work_System.pdf",
    category: "Indian Petroleum Safety Standard",
    document_type: "STATUTORY",
    source_org: "OISD",
    source_authority: "Oil Industry Safety Directorate (Govt. of India)",
    version: "Rev 4",
    chunk_count: 114,
    embedding_model: "text-embedding-3-small",
    uploaded_at: "2026-08-20T11:00:00Z",
    status: "INDEXED",
    vector_count: 114,
    summary: "Oil Industry Safety Directorate standards governing cold work, hot work, vessel entry, and electrical isolation permits across upstream and downstream units.",
  },
  {
    id: "doc-004",
    title: "API Recommended Practice 521: Pressure-Relieving & Depressuring Systems",
    filename: "API_RP_521_Pressure_Relief_Systems.pdf",
    category: "Engineering Standard",
    document_type: "ENGINEERING",
    source_org: "API",
    source_authority: "American Petroleum Institute",
    version: "7th Edition",
    chunk_count: 186,
    embedding_model: "text-embedding-3-small",
    uploaded_at: "2026-08-22T16:45:00Z",
    status: "INDEXED",
    vector_count: 186,
    summary: "Design and operational verification guide for pressure-relief valves, rupture disks, flare knockout drums, and emergency depressurization.",
  },
  {
    id: "doc-005",
    title: "IEC 61511: Functional Safety - Safety Instrumented Systems for the Process Industry",
    filename: "IEC_61511_Safety_Instrumented_Systems.pdf",
    category: "Automation & Interlocks",
    document_type: "TECHNICAL",
    source_org: "IEC",
    source_authority: "International Electrotechnical Commission",
    version: "Ed. 2.1",
    chunk_count: 210,
    embedding_model: "text-embedding-3-small",
    uploaded_at: "2026-08-25T10:20:00Z",
    status: "INDEXED",
    vector_count: 210,
    summary: "SIL determination, proof-testing intervals, bypass management, and emergency shutdown valve (ESD) maintenance protocols.",
  },
  {
    id: "doc-006",
    title: "DGMS Circular No. 04 of 2022: Marine & Heavy Industrial Rigging Safety",
    filename: "DGMS_Circular_04_2022_Rigging_Lifting.pdf",
    category: "Statutory Guideline",
    document_type: "DIRECTIVE",
    source_org: "DGMS",
    source_authority: "Directorate General of Mines Safety (Govt. of India)",
    version: "04-2022",
    chunk_count: 76,
    embedding_model: "text-embedding-3-small",
    uploaded_at: "2026-08-28T08:00:00Z",
    status: "INDEXED",
    vector_count: 76,
    summary: "Statutory guidelines on certified lifting gear, color-coding cycles, non-destructive testing of crane hooks, and exclusion zone enforcement.",
  },
];
